const WORDS_DB = {
  "B1": [
    ["hospital", "bệnh viện", "ˈhɑˌspɪtəɫ"],
    ["weather", "thời tiết", "ˈwɛðɝ"],
    ["holiday", "kỳ nghỉ", "ˈhɑɫəˌdeɪ"],
    ["kitchen", "nhà bếp", "ˈkɪtʃən"],
    ["morning", "buổi sáng", "ˈmɔɹnɪŋ"],
    ["market", "chợ", "ˈmɑɹkət"],
    ["teacher", "giáo viên", "ˈtitʃɝ"],
    ["family", "gia đình", "ˈfæməɫi"],
    ["hungry", "đói bụng", "ˈhəŋɡɹi"],
    ["travel", "du lịch", "ˈtɹævəɫ"],
    ["forget", "quên", "fɝˈɡɛt"],
    ["borrow", "mượn", "ˈbɑˌɹoʊ"],
    ["arrive", "đến nơi", "ɝˈaɪv"],
    ["decide", "quyết định", "ˌdɪˈsaɪd"],
    ["neighbor", "hàng xóm", "ˈneɪbɝ"],
    ["yesterday", "hôm qua", "ˈjɛstɝˌdeɪ"],
    ["haven", "nơi trú ẩn", "ˈheɪvən"],
    ["accompany", "kèm theo", "əˈkəmpəni"],
    ["liberate", "giải phóng", "ˈɫɪˌbɝˌeɪt"],
    ["ache", "đau nhức", "ˈeɪk"],
    ["involved", "có liên quan", "ˌɪnˈvɑɫvd"],
    ["depart", "khởi hành", "dɪˈpɑɹt"],
    ["philosopher", "triết gia", "fəˈɫɑsəfɝ"],
    ["systematic", "thuộc hệ thống", "ˌsɪstəˈmætɪk"],
    ["able", "có năng lực", "ˈeɪbəɫ"],
    ["rubber", "cao su", "ˈɹəbɝ"],
    ["silk", "tơ ,lụa", "ˈsɪɫk"],
    ["supply", "cung cấp, đáp ứng, tiếp tế", "səˈpɫaɪ"],
    ["safely", "an toàn, chắc chắn, đáng tin", "ˈseɪfɫi"],
    ["hang", "treo, mắc", "ˈhæŋ"],
    ["outdoor", "ngoài trời, ở ngoài", "ˈaʊtˌdɔɹ"],
    ["controversial", "gây tranh cãi", "ˌkɑntɹəˈvɝʃəɫ"],
    ["intense", "mãnh liệt", "ˌɪnˈtɛns"],
    ["politics", "chính trị", "ˈpɑɫəˌtɪks"],
    ["locate", "xác định vị trí, định vị", "ˈɫoʊˌkeɪt"],
    ["patrol", "tuần tra", "pəˈtɹoʊɫ"],
    ["highly", "tốt, cao", "ˈhaɪɫi"],
    ["residential", "ký túc xá", "ˌɹɛzɪˈdɛnʃəɫ"],
    ["exchange", "tráo đổi", "ɪksˈtʃeɪndʒ"],
    ["resource", "tài nguyên", "ˈɹisɔɹs"],
    ["brotherhood", "hội gì?", "ˈbɹəðɝˌhʊd"],
    ["interval", "khoảng thời gian", "ˈɪntɝvəɫ"],
    ["curly", "quăn, xoắn", "ˈkɝɫi"],
    ["smell", "ngửi", "ˈsmɛɫ"],
    ["sour", "chua, cỏ vị giấm", "ˈsaʊɝ"],
    ["secret", "điều bí mật", "ˈsikɹət"],
    ["peanut", "di chuyển theo hình đậu phộng", "ˈpiˌnət"],
    ["sunrise", "mặt trời mọc:", "ˈsənˌɹaɪz"],
    ["barbecue", "tiệc nướng ngoài trời", "ˈbɑɹbɪkˌju"],
    ["mend", "sửa chữa", "ˈmɛnd"],
    ["separation", "chia cắt, phân ly", "ˌsɛpɝˈeɪʃən"],
    ["atmosphere", "khí quyến", "ˈætməsˌfɪɹ"],
    ["standard", "tiêu chuẩn", "ˈstændɝd"],
    ["surface", "bể mặt", "ˈsɝfəs"],
    ["comma", "dấu phẩy", "ˈkɑmə"],
    ["tiring", "mệt mỏi", "ˈtaɪɹɪŋ"],
    ["equality", "bình đẳng", "ɪˈkwɑɫəti"],
    ["excitement", "sự kích thích, sự kích động", "ɪkˈsaɪtmənt"],
    ["click", "bấm chuột", "ˈkɫɪk"],
    ["ship", "tàu, tàu thủy", "ˈʃɪp"],
    ["uplifted", "được nâng lên", "ˈəpɫɪftɪd"],
    ["uninterested", "không quan tâm", "əˈnɪntɹəstɪd"],
    ["publisher", "nhà xuất bản", "ˈpəbɫɪʃɝ"],
    ["notorious", "khét tiếng", "noʊˈtɔɹiəs"],
    ["enable", "kích hoạt", "ɛˈneɪbəɫ"],
    ["record", "danh mục của kỷ lục hiện tại", "ˈɹɛkɝd"],
    ["embarrass", "làm rắc rối, gây khó khăn", "ɪmˈbɛɹəs"],
    ["explosion", "phát triển ồ ạt", "ɪksˈpɫoʊʒən"],
    ["appeal", "lời kêu gọi", "əˈpiɫ"],
    ["stripe", "sọc, vằn, viển", "ˈstɹaɪp"],
    ["geography", "địa lý, khoa địa lý", "dʒiˈɑɡɹəfi"],
    ["accomplish", "hoàn thành", "əˈkɑmpɫɪʃ"],
    ["connect", "kết nối", "kəˈnɛkt"],
    ["swarm", "tự tập bầy", "ˈswɔɹm"],
    ["skyscraper", "nhà chọc trời", "ˈskaɪsˌkɹeɪpɝ"],
    ["reality", "sự thật, thực tế, thực tại", "ˌɹiˈæɫəˌti"],
    ["worthwhile", "đáng giá", "ˈwɝθˈwaɪɫ"],
    ["intend", "ý định, có ý định", "ˌɪnˈtɛnd"],
    ["humid", "ẩm", "ˈhjuməd"],
    ["lighter", "xà lan (xuồng) chở hàng", "ˈɫaɪtɝ"],
    ["shallow", "nông, cạn", "ˈʃæɫoʊ"],
    ["abandon", "từ bỏ", "əˈbændən"],
    ["abnormal", "không bình thường", "æbˈnɔɹməɫ"],
    ["aboard", "trên boong", "əˈbɔɹd"],
    ["aborigine", "thổ dân", "ˌæbɝˈɪdʒəni"],
    ["above", "ở trên", "əˈbəv"],
    ["absence", "vắng mặt", "ˈæbsəns"],
    ["absent", "nghỉ", "ˈæbsənt"],
    ["absolute", "tuyệt đối", "ˈæbsəˌɫut"],
    ["absolutely", "hoàn toàn", "ˌæbsəˈɫutɫi"],
    ["absorb", "hấp thu", "əbˈzɔɹb"],
    ["abstract", "Trìu tượng", "ˈæbˌstɹækt"],
    ["abundance", "sung túc", "əˈbəndəns"],
    ["abundant", "[sự", "əˈbəndənt"],
    ["academic", "học thuật", "ˌækəˈdɛmɪk"],
    ["academy", "Viện hàn lâm", "əˈkædəmi"],
    ["accent", "trọng âm", "ˈækˌsɛnt"],
    ["acceptance", "chấp thuận", "ækˈsɛptəns"],
    ["access", "truy cập", "ˈækˌsɛs"],
    ["accessible", "dấu phẩy", "ækˈsɛsəbəɫ"],
    ["accessory", "vật phụ thuộc", "ækˈsɛsɝi"],
    ["accidental", "tình cờ", "ˌæksəˈdɛnəɫ"],
    ["accidentally", "ngẫu nhiên", "ˌæksəˈdɛnəɫi"],
    ["courageous", "Can đảm", "kɝˈeɪdʒəs"],
    ["accountant", "nhân viên kế toán", "əˈkaʊntənt"],
    ["accuracy", "tính chính xác", "ˈækjɝəsi"],
    ["accurate", "chính xác, đúng đắn", "ˈækjɝət"],
    ["accurately", "đúng đắn", "ˈækjɝətɫi"],
    ["accuse", "tố cáo", "əkˈjuz"],
    ["craft", "nghề thủ công", "ˈkɹæft"],
    ["acknowledge", "công nhận", "ækˈnɑɫɪdʒ"],
    ["acquaintance", "quan hệ nhân sinh", "əˈkweɪntəns"],
    ["acquire", "đạt được", "əˈkwaɪɝ"],
    ["act", "hành vi", "ˈækt"],
    ["active", "đã kích hoạt", "ˈæktɪv"],
    ["actress", "nữ diễn viên", "ˈæktɹəs"],
    ["adapt", "lắp vào", "əˈdæpt"],
    ["address", "tương tự", "ˈæˌdɹɛs"],
    ["addressee", "người nhận điện", "ˌædɹɛˈsi"],
    ["administration", "Quản trị", "ædˌmɪnɪˈstɹeɪʃən"],
    ["admiration", "thán phục", "ˌædmɝˈeɪʃən"],
    ["admission", "nhận vào", "ædˈmɪʃən"],
    ["adopt", "nhận nuôi", "əˈdɑpt"],
    ["adorable", "Đáng yêu", "əˈdɔɹəbəɫ"],
    ["adverb", "Trạng từ", "ˈædvɝb"],
    ["adverbial", "trạng từ", "ædˈvɝbiəɫ"],
    ["advert", "quảng cáo", "ˈædvɝt"],
    ["advertise", "báo cho biết, báo cho biết trước", "ˈædvɝˌtaɪz"],
    ["aerobics", "Thể dục nhịp điệu", "ɝˈoʊbɪks"],
    ["affect", "làm ảnh hưởng, tác động đến", "əˈfɛkt"],
    ["affection", "sự ảnh hưởng", "əˈfɛkʃən"],
    ["afford", "cỏ thế, cỏ đủ khả năng, điểu kiện (làm gì)", "əˈfɔɹd"],
    ["crash", "rơi (máy bay), phá sản, sụp đổ", "ˈkɹæʃ"],
    ["afterward", "Sau đó?", "ˈæftɝwɝd"],
    ["afterwards", "sau này, về sau, rồi thì, sau đấy", "ˈæftɝwɝdz"],
    ["agenda", "chương trình nghị sự", "əˈdʒɛndə"],
    ["aggressive", "xâm lược, hung hăng", "əˈɡɹɛsɪv"],
    ["agreement", "sự đồng ý, tán thành", "əˈɡɹimənt"],
    ["agricultural", "nông nghiệp", "ˌæɡɹəˈkəɫtʃɝəɫ"],
    ["agriculture", "nông nghiệp", "ˈæɡɹɪˌkəɫtʃɝ"],
    ["aid", "sự giúp đỡ", "ˈeɪd"],
    ["aim", "sự nhắm (bắn), mục tiêu, ý định", "ˈeɪm"],
    ["airline", "hãng hàng không", "ˈɛɹˌɫaɪn"],
    ["alarm", "báo động, báo nguy", "əˈɫɑɹm"],
    ["alcohol", "rượu cồn", "ˈæɫkəˌhɑɫ"],
    ["alcoholic", "rượu", "ˌæɫkəˈhɑɫɪk"],
    ["alike", "như nhau", "əˈɫaɪk"],
    ["allergic", "(thuộc) dị ứng", "əˈɫɝdʒɪk"],
    ["allowance", "phụ cấp", "əˈɫaʊəns"],
    ["aloud", "lớn tiếng, to tiếng", "əˈɫaʊd"],
    ["alphabet", "bảng chữ cái, bước đầu, điểu cơ bản", "ˈæɫfəˌbɛt"],
    ["alternative", "Thay thế", "ɔɫˈtɝnətɪv"],
    ["altogether", "hoàn toàn, hầu như", "ˌɔɫtəˈɡɛðɝ"],
    ["amazed", "kinh ngạc, sửng sốt", "əˈmeɪzd"],
    ["amazing", "kinh ngạc, sửng sốt", "əˈmeɪzɪŋ"],
    ["ambulance", "xe cấp cứu", "ˈæmbjəɫəns"],
    ["amount", "phí", "əˈmaʊnt"],
    ["amusing", "vui thích", "əmˈjuzɪŋ"],
    ["analysis", "Phân tích", "əˈnæɫəsəs"],
    ["anger", "sự tức giận, sự giận dữ", "ˈæŋɡɝ"],
    ["angle", "góc", "ˈæŋɡəɫ"],
    ["animated", "được hoạt họa", "ˈænəˌmeɪtɪd"],
    ["animation", "hoạt họa", "ˌænəˈmeɪʃən"],
    ["announce", "thông báo", "əˈnaʊns"],
    ["announcement", "thông báo", "əˈnaʊnsmənt"],
    ["annoyance", "khó chịu", "əˈnɔɪəns"],
    ["annoyed", "bị khỏ chịu, bực mình, bị quấy rầy", "əˈnɔɪd"],
    ["annual", "hàng năm, từng năm", "ˈænjuəɫ"],
    ["annually", "mỗi năm", "ˈænjuəɫi"],
    ["ant", "kiến", "ˈænt"],
    ["anti", "chống lại", "ˈænˌtaɪ"],
    ["anxiety", "mối lo âu, sự lo lắng", "æŋˈzaɪəti"],
    ["anxiously", "lo âu, lo lắng, băn khoăn", "ˈæŋkʃəsɫi"],
    ["anyhow", "Mr. Lance.", "ˈɛniˌhaʊ"],
    ["ape", "Liên họ Người", "ˈeɪp"],
    ["apology", "sự xin lỗi", "əˈpɑɫəˌdʒi"],
    ["apparent", "rõ ràng, rành mạch", "əˈpɛɹənt"],
    ["appetite", "sự thèm ăn", "ˈæpəˌtaɪt"],
    ["applaud", "[Vỗ tay]", "əˈpɫɔd"],
    ["applause", "Vỗ tay nào...", "əˈpɫɔz"],
    ["creator", "tác giả", "kɹiˈeɪtɝ"],
    ["appoint", "bồ nhiệm, chỉ định, chọn", "əˈpɔɪnt"],
    ["appreciation", "sự tăng giá", "əˌpɹiʃiˈeɪʃən"],
    ["approach", "tiếp cận", "əˈpɹoʊtʃ"],
    ["approval", "phê duyệt", "əˈpɹuvəɫ"],
    ["approve", "tán thành, đồng ý, chấp thuận", "əˈpɹuv"],
    ["approximately", "khoảng chừng", "əˈpɹɑksəmətɫi"],
    ["architect", "kiến trúc sư", "ˈɑɹkəˌtɛkt"],
    ["arise", "xuất hiện, nảy ra, nảy sinh ra", "ɝˈaɪz"],
    ["arithmetic", "số học", "ˌɛɹɪθˈmɛtɪk"],
    ["arm", "trên", "ˈɑɹm"],
    ["army", "quân đội", "ˈɑɹmi"],
    ["arrange", "sắp xếp, sắp đặt", "ɝˈeɪndʒ"],
    ["arrangement", "sự sắp xếp, sắp đặt, sự sửa soạn", "ɝˈeɪndʒmənt"],
    ["arrest", "bắt giữ", "ɝˈɛst"],
    ["arrival", "đến nơi", "ɝˈaɪvəɫ"],
    ["arrow", "tên, mũi tên", "ˈæɹoʊ"],
    ["artist", "nghệ sĩ", "ˈɑɹtəst"],
    ["artistic", "thuộc nghệ thuật, thuộc mỹ thuật", "ɑɹˈtɪstɪk"],
    ["ashamed", "ngượng, xấu hồ", "əˈʃeɪmd"],
    ["aside", "về một bẽn, sang một bẽn", "əˈsaɪd"],
    ["aspect", "vẻ bể ngoài, diện mạo", "ˈæsˌpɛkt"],
    ["crisis", "khủng hoảng", "ˈkɹaɪsəs"],
    ["assign", "Gán", "əˈsaɪn"],
    ["assignment", "phân công", "əˈsaɪnmənt"],
    ["assist", "giúp đỡ", "əˈsɪst"],
    ["assistance", "sự giúp đỡ", "əˈsɪstəns"],
    ["assistant", "phụ tá", "əˈsɪstənt"],
    ["associate", "liên kết", "əˈsoʊsiˌeɪt"],
    ["assume", "mang, khoác", "əˈsum"],
    ["astronomer", "Nhà thiên văn học", "əˈstɹɑnəmɝ"],
    ["athletic", "Khỏe mạnh", "æθˈɫɛtɪk"],
    ["atlantic", "Đại Tây Dương", "ətˈɫænɪk"],
    ["atomic", "nguyên tử", "əˈtɑmɪk"],
    ["attach", "gắn, dán, trói, buộc", "əˈtætʃ"],
    ["attachment", "quyến luyến", "əˈtætʃmənt"],
    ["attain", "đạt được, hoàn thành", "əˈteɪn"],
    ["attempt", "cố gắng, thử", "əˈtɛmpt"],
    ["attend", "tham dự", "əˈtɛnd"],
    ["attract", "thu hút, hấp dẫn", "əˈtɹækt"],
    ["attraction", "sức hút", "əˈtɹækʃən"],
    ["authority", "uy quyển, quyển lực", "əˈθɔɹəti"],
    ["auxiliary", "bổ trợ, phụ", "ɑɡˈzɪɫiɛɹi"],
    ["available", "Còn trống", "əˈveɪɫəbəɫ"],
    ["avenue", "đại lộ", "ˈævəˌnu"],
    ["award", "phần thưởng", "əˈwɔɹd"],
    ["aware", "nhận thức", "əˈwɛɹ"],
    ["awareness", "nhận thức", "əˈwɛɹnəs"],
    ["awesome", "tuyệt vời", "ˈɑsəm"],
    ["awkward", "vụng về, lung túng", "ˈɑkwɝd"],
    ["babysit", "Bảo mẫu", "ˈbeɪbisɪt"],
    ["babysitter", "bảo mẫu", "ˈbeɪbiˌsɪtɝ"],
    ["back", "quay lại", "ˈbæk"],
    ["backache", "bệnh đau lưng", "ˈbæˌkeɪk"],
    ["backpack", "ba lô", "ˈbækˌpæk"],
    ["backpacker", "du khách ba lô", "ˈbækˌpækɝ"],
    ["backpacking", "Du lịch bụi", "ˈbækˌpækɪŋ"],
    ["bacon", "thịt lợn muối xông khói", "ˈbeɪkən"],
    ["baggage", "hành lý", "ˈbæɡədʒ"],
    ["baker", "người làm bánh mỳ", "ˈbeɪkɝ"],
    ["bakery", "tiệm bánh", "ˈbeɪkɝi"],
    ["critic", "nhà phê bình", "ˈkɹɪtɪk"],
    ["bald", "lông", "ˈbɔɫd"],
    ["bandage", "dải băng", "ˈbændɪdʒ"],
    ["cultivate", "cày cấy", "ˈkəɫtəˌveɪt"],
    ["critical", "phê bình", "ˈkɹɪtɪkəɫ"],
    ["bare", "bóc trần", "ˈbɛɹ"],
    ["barely", "- Chắc chắn rồi.", "ˈbɛɹɫi"],
    ["bark", "Vỏ cây", "ˈbɑɹk"],
    ["barman", "Pha chế rượu", "ˈbɑɹmən"],
    ["barrel", "thùng rượu", "ˈbæɹəɫ"],
    ["base", "cơ sở, cơ bản, nền móng", "ˈbeɪs"],
    ["basement", "móng cơ bản", "ˈbeɪsmənt"],
    ["basin", "bồn", "ˈbeɪsən"],
    ["basis", "nền tảng, cơ sở", "ˈbeɪsəs"],
    ["bat", "Đánh bóng", "ˈbæt"],
    ["bathe", "Tắm", "ˈbeɪð"],
    ["battle", "trận đánh, chiến thuật", "ˈbætəɫ"],
    ["beard", "râu", "ˈbɪɹd"],
    ["beast", "động vật", "ˈbist"],
    ["beautifully", "tốt đẹp, đáng hài lỏng", "ˈbjutəfɫi"],
    ["beaver", "Hải li", "ˈbivɝ"],
    ["bedside", "đầu giường", "ˈbɛdˌsaɪd"],
    ["behalf", "sự thay mặt", "bɪˈhæf"],
    ["behave", "đối xử, ăn ở, cư xử", "bɪˈheɪv"],
    ["belief", "lòng tin", "bɪˈɫif"],
    ["beneath", "ở dưới, dưới thấp", "bɪˈniθ"],
    ["benefit", "lợi ích, lãi", "ˈbɛnəfɪt"],
    ["bent", "khiếu, sở thích, khuynh hướng", "ˈbɛnt"],
    ["besides", "bên cạnh đó", "ˌbiˈsaɪdz"],
    ["bet", "đặt cược", "ˈbɛt"],
    ["bilingual", "chương trình giáo dục", "baɪˈɫɪŋɡwəɫ"],
    ["bill", "hóa đơn", "ˈbɪɫ"],
    ["bin", "thùng", "ˈbɪn"],
    ["biochemistry", "hóa sinh", "ˌbaɪoʊˈkɛməstɹi"],
    ["biography", "Tiểu sử", "baɪˈɑɡɹəfi"],
    ["biology", "sinh học", "baɪˈɑɫədʒi"],
    ["bishop", "Giám mục", "ˈbɪʃəp"],
    ["bite", "cắn", "ˈbaɪt"],
    ["bitter", "đắng cay, chua xót", "ˈbɪtɝ"],
    ["blame", "trách cứ", "ˈbɫeɪm"],
    ["bleed", "xả", "ˈbɫid"],
    ["bless", "Ban Phước", "ˈbɫɛs"],
    ["blessing", "đều đáng mừng", "ˈbɫɛsɪŋ"],
    ["blind", "mù", "ˈbɫaɪnd"],
    ["block", "chặn", "ˈbɫɑk"],
    ["crop", "vụ mùa", "ˈkɹɑp"],
    ["crossing", "mua ngang bán tắt", "ˈkɹɔsɪŋ"],
    ["blush", "Má hồng", "ˈbɫəʃ"],
    ["board", "tấm ván", "ˈbɔɹd"],
    ["boast", "lời nói khoe khoang", "ˈboʊst"],
    ["bold", "đậm", "ˈboʊɫd"],
    ["boldly", "mạnh dạn", "ˈboʊɫdɫi"],
    ["crossroads", "W.205 (đường giao nhau)", "ˈkɹɔsˌɹoʊdz"],
    ["bond", "nối", "ˈbɑnd"],
    ["book", "sách", "ˈbʊk"],
    ["booking", "việc mua vé trước", "ˈbʊkɪŋ"],
    ["boom", "bùng nổ", "ˈbum"],
    ["boot", "giày ống", "ˈbut"],
    ["border", "bờ, mép, vỉa, lể (đường)", "ˈbɔɹdɝ"],
    ["bore", "buồn chán, buồn tẻ", "ˈbɔɹ"],
    ["boredom", "sự buồn tẻ", "ˈbɔɹdəm"],
    ["bother", "làm phiền, quấy rầy", "ˈbɑðɝ"],
    ["bound", "trái phiếu", "ˈbaʊnd"],
    ["bow", "mũi tàu", "ˈbaʊ"],
    ["bowl", "cái bát", "ˈboʊɫ"],
    ["boxing", "đấm bốc", "ˈbɑksɪŋ"],
    ["bracelet", "Vòng tay", "ˈbɹeɪsɫət"],
    ["brainstorming", "sự thảo luận tự do không hạn chế", "ˈbɹeɪnˌstɔɹmɪŋ"],
    ["branch", "chi nhánh", "ˈbɹæntʃ"],
    ["brass", "trả hết", "ˈbɹæs"],
    ["bravely", "dũng cảm", "ˈbɹeɪvɫi"],
    ["breakthrough", "bền vững.", "ˈbɹeɪkˌθɹu"],
    ["breast", "ngực, vú", "ˈbɹɛst"],
    ["breath", "hơi thở", "ˈbɹɛθ"],
    ["crow", "Quạ", "ˈkɹoʊ"],
    ["breeding", "sự sinh sản", "ˈbɹidɪŋ"],
    ["brick", "gạch", "ˈbɹɪk"],
    ["brief", "ngắn, gọn, vắn tắt", "ˈbɹif"],
    ["briefly", "ngắn, gọn, vắn tắt, tóm tắt", "ˈbɹifɫi"],
    ["brightly", "tươi sáng", "ˈbɹaɪtɫi"],
    ["broad", "rộng", "ˈbɹɔd"],
    ["broadcast", "quảng bá", "ˈbɹɔdˌkæst"],
    ["cruel", "độc ác, tàn nhẫn", "ˈkɹuəɫ"],
    ["bronze", "đồng", "ˈbɹɑnz"],
    ["bubble", "bong bỏng, bọt, tăm", "ˈbəbəɫ"],
    ["buddy", "Buddy ... Buddy ...", "ˈbədi"],
    ["builder", "nhà thầu xây cất", "ˈbɪɫdɝ"],
    ["bull", "tư tưởng giá lên", "ˈbʊɫ"],
    ["bullet", "đạn", "ˈbʊɫət"],
    ["bulletin", "thông báo", "ˈbʊɫɪtən"],
    ["bump", "dời chỗ", "ˈbəmp"],
    ["bunch", "búi, chùm, bỏ, cụm, buồng", "ˈbəntʃ"],
    ["burden", "gánh nặng", "ˈbɝdən"],
    ["bureau", "văn phòng", "ˈbjʊɹoʊ"],
    ["burglar", "Tên trộm", "ˈbɝɡɫɝ"],
    ["burn", "đốt cháy", "ˈbɝn"],
    ["burning", "sự nung", "ˈbɝnɪŋ"],
    ["burst", "nồ, nồ tung (bom, đạn)", "ˈbɝst"],
    ["bust", "vỡ nợ", "ˈbəst"],
    ["but", "nhưng", "ˈbət"],
    ["butcher", "người hàng thịt", "ˈbʊtʃɝ"],
    ["buyer", "bên mua", "ˈbaɪɝ"],
    ["cabbage", "cải bắp", "ˈkæbədʒ"],
    ["crush", "ép, vắt, đè nát", "ˈkɹəʃ"],
    ["cage", "phòng quỹ", "ˈkeɪdʒ"],
    ["calculate", "tính toán", "ˈkæɫkjəˌɫeɪt"],
    ["calculation", "cánh tính", "ˌkæɫkjəˈɫeɪʃən"],
    ["calculator", "máy tính", "ˈkæɫkjəˌɫeɪtɝ"],
    ["calf", "Bê con", "ˈkæf"],
    ["caller", "Người gọi", "ˈkɔɫɝ"],
    ["calm", "yên lặng, làm dịu đi, sự êm ả", "ˈkɑɫm"],
    ["calmness", "sự bình tĩnh.", "ˈkɑɫmnəs"],
    ["camel", "con lạc đà", "ˈkæməɫ"],
    ["campsite", "Trại", "ˈkæmpˌsaɪt"],
    ["canal", "ống kênh đào", "kəˈnæɫ"],
    ["cancel", "hủy bỏ", "ˈkænsəɫ"],
    ["cancer", "bệnh ung thư", "ˈkænsɝ"],
    ["candle", "nến", "ˈkændəɫ"],
    ["canned", "vô hộp", "ˈkænd"],
    ["canteen", "nhà ăn", "kænˈtin"],
    ["capable", "có năng lực", "ˈkeɪpəbəɫ"],
    ["capacity", "năng lực, khả năng tiếp thu, năng suất", "kəˈpæsəti"],
    ["capsule", "vỏ", "ˈkæpsəɫ"],
    ["capture", "bắt giữ", "ˈkæptʃɝ"],
    ["care", "chăm sóc", "ˈkɛɹ"],
    ["career", "nghề nghiệp", "kɝˈɪɹ"],
    ["careless", "sơ suất, cầu thả", "ˈkɛɹɫəs"],
    ["carelessly", "bất cần", "ˈkɛɹɫəsɫi"],
    ["carelessness", "vô ý", "ˈkɛɹɫəsnəs"],
    ["carpet", "tấm thảm", "ˈkɑɹpət"],
    ["carriage", "xe (lửa) chở khách", "ˈkæɹɪdʒ"],
    ["carton", "thùng cattong", "ˈkɑɹtən"],
    ["casual", "tình cờ", "ˈkæʒəwəɫ"],
    ["category", "hạngmục", "ˈkætəˌɡɔɹi"],
    ["cattle", "gia súc", "ˈkætəɫ"],
    ["caution", "cảnh báo", "ˈkɑʃən"],
    ["cautious", "Cẩn thân", "ˈkɔʃəs"],
    ["cave", "lỗ (trong fomat)", "ˈkeɪv"],
    ["celebrity", "người nổi tiếng", "səˈɫɛbɹɪti"],
    ["cell", "mây dông", "ˈsɛɫ"],
    ["central", "trung tâm", "ˈsɛntɹəɫ"],
    ["ceremony", "nghi thức, nghi lễ", "ˈsɛɹəˌmoʊni"],
    ["certainty", "chắc chắn,", "ˈsɝtənti"],
    ["challenging", "khó khăn để thực hiện.", "ˈtʃæɫəndʒɪŋ"],
    ["champion", "quán quân", "ˈtʃæmpiən"],
    ["channel", "kênh (TV, radio), eo biến", "ˈtʃænəɫ"],
    ["chaos", "hỗn loạn.", "ˈkeɪɑs"],
    ["charge", "nhiệm vụ, trách nhiệm", "ˈtʃɑɹdʒ"],
    ["chariot", "Xe ngựa chiến", "ˈtʃɛɹiət"],
    ["charity", "từ thiện", "ˈtʃɛɹɪti"],
    ["charm", "Nhan sắc", "ˈtʃɑɹm"],
    ["chat", "trò chuyện", "ˈtʃæt"],
    ["checkout", "thanh toán", "ˈtʃɛˌkaʊt"],
    ["cheerful", "vui mừng, phấn khởi", "ˈtʃɪɹfəɫ"],
    ["chemical", "hóa chất", "ˈkɛməkəɫ"],
    ["chemist", "nhà hỏa học", "ˈkɛmɪst"],
    ["chemistry", "hóa học", "ˈkɛməstɹi"],
    ["cherish", "nuôi", "ˈtʃɛɹɪʃ"],
    ["chief", "thủ lĩnh, lãnh tụ, xếp", "ˈtʃif"],
    ["choir", "Hợp xướng", "ˈkwaɪɝ"],
    ["choke", "làm tắc thở", "ˈtʃoʊk"],
    ["christian", "Cơ Đốc nhân", "ˈkɹɪstʃən"],
    ["chronological", "thời gian", "ˌkɹɑnəˈɫɑdʒɪkəɫ"],
    ["chuckle", "Uh, trông như cậu đến từ Bắc Cực ấy.", "ˈtʃəkəɫ"],
    ["circle", "hình tròn", "ˈsɝkəɫ"],
    ["circular", "tròn", "ˈsɝkjəɫɝ"],
    ["circus", "Xiếc", "ˈsɝkəs"],
    ["citizenship", "quốc tịch", "ˈsɪtɪzənˌʃɪp"],
    ["civil", "(thuộc) công dân", "ˈsɪvəɫ"],
    ["claim", "yêu sách", "ˈkɫeɪm"],
    ["classical", "CỔ ĐIỂN", "ˈkɫæsɪkəɫ"],
    ["classify", "Sắp xếp", "ˈkɫæsəˌfaɪ"],
    ["clear", "lau chùi, quét dọn", "ˈkɫɪɹ"],
    ["cliff", "vách đá (CLIFF)", "ˈkɫɪf"],
    ["climate", "khí hậu, thời tiết", "ˈkɫaɪmət"],
    ["climber", "người leo núi", "ˈkɫaɪmɝ"],
    ["clinic", "phòng khám", "ˈkɫɪnɪk"],
    ["clip", "Cắt Xén", "ˈkɫɪp"],
    ["closely", "chặt chẽ, kỹ lưỡng, tỉ mỉ", "ˈkɫoʊsɫi"],
    ["coal", "than đá", "ˈkoʊɫ"],
    ["coast", "bờ biến", "ˈkoʊst"],
    ["coastal", "Bờ biển", "ˈkoʊstəɫ"],
    ["cod", "cá tuyết", "ˈkɑd"],
    ["coffin", "lớp vỏ", "ˈkɔfɪn"],
    ["collapse", "Sụt lở", "kəˈɫæps"],
    ["collar", "vòng đai", "ˈkɑɫɝ"],
    ["columnist", "người viết chuyên mục", "ˈkɑɫəmnəst"],
    ["combination", "sự kết hợp", "ˌkɑmbəˈneɪʃən"],
    ["combine", "kết hợp, phối hợp", "ˈkɑmbaɪn"],
    ["comedian", "diễn viên hài", "kəˈmidiən"],
    ["comedy", "hài kịch", "ˈkɑmədi"],
    ["comet", "sao chổi", "ˈkɑmət"],
    ["comfort", "an ủi, động viên", "ˈkəmfɝt"],
    ["command", "lệnh", "kəˈmænd"],
    ["comment", "Bình luận", "ˈkɑmɛnt"],
    ["commercial", "buôn bán, thương mại", "kəˈmɝʃəɫ"],
    ["commit", "ủy nhiệm, ủy thác", "kəˈmɪt"],
    ["commonly", "thông thường, bình thường", "ˈkɑmənɫi"],
    ["companion", "bạn đồng hành", "kəmˈpænjən"],
    ["comparison", "so sánh", "kəmˈpɛɹəsən"],
    ["competitive", "cạnh tranh", "kəmˈpɛtətɪv"],
    ["cucumber", "dưa chuột", "ˈkjukəmbɝ"],
    ["complement", "số người biên chế quy định (trên tàu)", "ˈkɑmpɫəmənt"],
    ["complete", "hoàn thành", "kəmˈpɫit"],
    ["completely", "hoàn thành, đầy đủ", "kəmˈpɫitɫi"],
    ["complex", "phức tạp", "ˈkɑmpɫɛks"],
    ["complicate", "làm phức tạp, rắc rối", "ˈkɑmpɫəˌkeɪt"],
    ["complicated", "phức tạp, rắc rối", "ˈkɑmpɫəˌkeɪtəd"],
    ["compliment", "Đúc sẵn", "ˈkɑmpɫəmɛnt"],
    ["compose", "Viết tin nhắn", "kəmˈpoʊz"],
    ["composition", "về Gia đình", "ˌkɑmpəˈzɪʃən"],
    ["compound", "hợp thể", "ˈkɑmpaʊnd"],
    ["compromise", "thỏa hiệp", "ˈkɑmpɹəˌmaɪz"],
    ["concentration", "sự tập trung, nơi tập trung", "ˌkɑnsənˈtɹeɪʃən"],
    ["concept", "Khái niệm", "ˈkɑnsɛpt"],
    ["concerned", "có liên quan", "kənˈsɝnd"],
    ["conclude", "kết luận, chấm dứt (công việc)", "kənˈkɫud"],
    ["conclusion", "sự kết thúc, sự kết luận, phần kết luận", "kənˈkɫuʒən"],
    ["conduct", "hạnh kiểm", "ˈkɑndəkt"],
    ["confidence", "tin tưởng, tin cậy, tự tin", "ˈkɑnfədəns"],
    ["confirm", "xác nhận, chứng thực", "kənˈfɝm"],
    ["confirmation", "thư xác nhận", "ˌkɑnfɝˈmeɪʃən"],
    ["conflict", "xung đột, va chạm", "ˈkɑnfɫɪkt"],
    ["confusing", "khó hiếu, gây bối rối", "kənˈfjuzɪŋ"],
    ["confusion", "lộn xộn, rối loạn", "kənˈfjuʒən"],
    ["congratulate", "chúc mừng", "kənˈɡɹætʃəˌɫeɪt"],
    ["conquer", "chinh phục", "ˈkɑŋkɝ"],
    ["conscious", "tỉnh táo, có ý thức", "ˈkɑnʃəs"],
    ["consequently", "Bởi thế, do đó, vậy thì, vì vậy, cho nên.", "ˈkɑnsəˌkwɛntɫi"],
    ["conservation", "bảo tồn", "ˌkɑnsɝˈveɪʃən"],
    ["conservative", "thận trọng, bảo thủ", "kənˈsɝvətɪv"],
    ["considerable", "đáng kế", "kənˈsɪdɝəbəɫ"],
    ["consideration", "cân nhắc, xem xét", "kənˌsɪdɝˈeɪʃən"],
    ["consonant", "Phụ âm", "ˈkɑnsənənt"],
    ["constantly", "kiên định", "ˈkɑnstəntɫi"],
    ["constitute", "cấu tạo", "ˈkɑnstəˌtut"],
    ["constitution", "thành phần", "ˌkɑnstəˈtuʃən"],
    ["construct", "xây dựng", "ˈkɑnstɹəkt"],
    ["construction", "xây dựng", "kənˈstɹəkʃən"],
    ["consume", "tiêu thụ", "kənˈsum"],
    ["consumer", "người tiêu dùng", "kənˈsumɝ"],
    ["consumption", "hàng ngày", "kənˈsəmpʃən"],
    ["contain", "chứa đựng, bao gồm", "kənˈteɪn"],
    ["continual", "liên tục", "kənˈtɪnjuəɫ"],
    ["continually", "Liên tục", "kənˈtɪnjuəɫi"],
    ["continuous", "liên tục, liên tiếp", "kənˈtɪnjuəs"],
    ["continuously", "liên tục, liên tiếp", "kənˈtɪnjuəsɫi"],
    ["contribute", "đóng góp, góp phần", "kənˈtɹɪbjut"],
    ["contribution", "sự đóng góp, sự góp phần", "ˌkɑntɹəbˈjuʃən"],
    ["control", "điều khiển", "kənˈtɹoʊɫ"],
    ["convey", "chuyển", "kənˈveɪ"],
    ["convince", "thuyết phục", "kənˈvɪns"],
    ["copyright", "quyền tác giả", "ˈkɑpiˌɹaɪt"],
    ["correction", "hiệu chỉnh", "kɝˈɛkʃən"],
    ["cotton", "bông, chỉ, sợi", "ˈkɑtən"],
    ["council", "hội đồng", "ˈkaʊnsəɫ"],
    ["count", "đếm", "ˈkaʊnt"],
    ["countless", "Vô số.", "ˈkaʊntɫəs"],
    ["county", "tỉnh", "ˈkaʊni"],
    ["courage", "dũng cảm, dũng khí", "ˈkɝədʒ"],
  ],
  "B2": [
    ["environment", "môi trường", "ɪnˈvaɪɹənmənt"],
    ["achievement", "thành tựu", "əˈtʃivmənt"],
    ["opportunity", "cơ hội", "ˌɑpɝˈtunəti"],
    ["challenge", "thử thách", "ˈtʃæɫəndʒ"],
    ["confident", "tự tin", "ˈkɑnfədənt"],
    ["negotiate", "đàm phán", "nəˈɡoʊʃiˌeɪt"],
    ["persuade", "thuyết phục", "pɝˈsweɪd"],
    ["reliable", "đáng tin cậy", "ɹiˈɫaɪəbəɫ"],
    ["ambitious", "tham vọng", "æmˈbɪʃəs"],
    ["look forward to", "mong chờ", "ˈɫʊk ˈfɔɹwɝd ˈtu"],
    ["give up", "từ bỏ", "ˈɡɪv ˈəp"],
    ["figure out", "tìm ra", "ˈfɪɡjɝ ˈaʊt"],
    ["consequence", "hậu quả", "ˈkɑnsəkwəns"],
    ["improve", "cải thiện", "ˌɪmˈpɹuv"],
    ["compete", "cạnh tranh", "kəmˈpit"],
    ["developing", "đang phát triển", "dɪˈvɛɫəpɪŋ"],
    ["tyranny", "chuyên chế", "ˈtɪɹəni"],
    ["round", "tròn, vòng quanh, xung quanh", "ˈɹaʊnd"],
    ["darling", "cục cưng", "ˈdɑɹɫɪŋ"],
    ["ample", "dồi dào, dư thừa", "ˈæmpəɫ"],
    ["weed", "cỏ dại", "ˈwid"],
    ["suppress", "lược bỏ", "səˈpɹɛs"],
    ["prosecute", "truy tố", "ˈpɹɑsəkˌjut"],
    ["snore", "ngáy", "ˈsnɔɹ"],
    ["uncommon", "đặc biệt", "ənˈkɑmən"],
    ["slang", "tiếng lóng", "ˈsɫæŋ"],
    ["bad-tempered", "xấu tính, dễ nồi cáu"],
    ["germ", "vi trùng", "ˈdʒɝm"],
    ["bombing", "đánh bom", "ˈbɑmɪŋ"],
    ["impressionist", "trường phái ấn tượng", "ˌɪmˈpɹɛʃənəst"],
    ["chase", "xua đuổi", "ˈtʃeɪs"],
    ["falter", "chùn bước", "ˈfɔɫtɝ"],
    ["literal", "bằng chữ:", "ˈɫɪtɝəɫ"],
    ["collocation", "sự sắp xếp", "kɑɫəˈkeɪʃən"],
    ["literally", "theo đúng nghĩa đen", "ˈɫɪtɝəɫi"],
    ["upgrade", "nâng cấp", "ˈəpˈɡɹeɪd"],
    ["formerly", "trước đây, thuở xưa", "ˈfɔɹmɝɫi"],
    ["imagery", "hình ảnh", "ˈɪmədʒɹi"],
    ["nonprofessional", "không chuyên nghiệp", "ˌnɑnpɹəˈfɛʃənəɫ"],
    ["cause", "gây ra:", "ˈkɑz"],
    ["welfare", "phúc lợi", "ˈwɛɫˌfɛɹ"],
    ["amongst", "giữa", "əˈməŋst"],
    ["educator", "nhà giáo dục", "ˈɛdʒəˌkeɪtɝ"],
    ["hospitality", "lòng hiếu khách", "ˌhɑspəˈtæɫəti"],
    ["therapy", "trị liệu", "ˈθɛɹəpi"],
    ["simplification", "sự đơn giản hóa", "ˌsɪmpɫəfɪˈkeɪʃən"],
    ["known", "đã xác định", "ˈnoʊn"],
    ["geographic", "địa dư", "ˌdʒiəˈɡɹæfɪk"],
    ["exhausting", "mệt mỏi", "ɪɡˈzɔstɪŋ"],
    ["mortal", "sinh tử", "ˈmɔɹtəɫ"],
    ["prominence", "tình trạng nổi lên", "ˈpɹɑmənəns"],
    ["interpreter", "thông dịch viên", "ˌɪnˈtɝpɹətɝ"],
    ["amazement", "kinh ngạc", "əˈmeɪzmənt"],
    ["adversity", "nghịch cảnh", "ædˈvɝsɪˌti"],
    ["emphatically", "dứt khoát", "ɛmˈfætɪkəɫi"],
    ["pancake", "bánh xèo", "ˈpænˌkeɪk"],
    ["inexperienced", "thiếu kinh nghiệm", "ɪnɪkˈspɪɹiənst"],
    ["persuasion", "thuyết Phục", "pɝˈsweɪʒən"],
    ["proudly", "một cách tự hào, một cách hãnh diện", "ˈpɹaʊdɫi"],
    ["reflective", "phản xạ", "ɹɪˈfɫɛktɪv"],
    ["dependable", "có thể tin được, đáng tin cậy", "dɪˈpɛndəbəɫ"],
    ["bookmark", "dấu trang", "ˈbʊkmɑɹk"],
    ["master", "thiết bị chính", "ˈmæstɝ"],
    ["conductor", "vật dẫn", "kənˈdəktɝ"],
    ["stick", "đạt được cái gì", "ˈstɪk"],
    ["posh", "hạng sang", "ˈpɑʃ"],
    ["pave", "lát", "ˈpeɪv"],
    ["anguish", "nỗi thống khổ", "ˈæŋɡwɪʃ"],
    ["sunbeam", "tia nắng", "ˈsənˌbim"],
    ["abuse", "lạm dụng", "əbˈjus"],
    ["micro", "siêu nhỏ", "ˈmaɪˌkɹoʊ"],
    ["confine", "giam giữ, hạn chế", "kənˈfaɪn"],
    ["translator", "phiên dịch viên", "tɹænˈsɫeɪtɝ"],
    ["outpatient", "bệnh nhân ngoạỉ trú", "ˈaʊtˌpeɪʃənt"],
    ["flesh", "thịt", "ˈfɫɛʃ"],
    ["wearisome", "mệt mỏi", "ˈwɪɹisəm"],
    ["strictly", "một cách nghiêm khắc", "ˈstɹɪktɫi"],
    ["divorce", "ly dị", "dɪˈvɔɹs"],
    ["abandoned", "đã từ bỏ", "əˈbændənd"],
    ["abnormally", "bất thường", "æbˈnɔɹməɫi"],
    ["abolish", "bãi bỏ, huỷ bỏ", "əˈbɑɫɪʃ"],
    ["aboriginal", "Dân Aboriginal", "ˌæbɝˈɪdʒənəɫ"],
    ["abruptly", "đột ngột", "əˈbɹəptɫi"],
    ["absentee", "người vắng mặt", "ˌæbsənˈti"],
    ["absurd", "sự trừu tượng hoá, sự trừu tượng", "əbˈsɝd"],
    ["core", "nòng cốt, hạt nhân", "ˈkɔɹ"],
    ["accommodation", "chỗ ở", "əˌkɑməˈdeɪʃən"],
    ["accordingly", "///", "əˈkɔɹdɪŋɫi"],
    ["accumulate", "tích lũy", "əkˈjumjəˌɫeɪt"],
    ["accusation", "buộc tội", "ˌækjəˈzeɪʃən"],
    ["cornerstone", "Viên đá đầu tiên", "ˈkɔɹnɝˌstoʊn"],
    ["acid", "axít", "ˈæsəd"],
    ["acquisition", "Chi trả để có khách hàng", "ˌækwəˈzɪʃən"],
    ["actively", "một cách tích cực", "ˈæktɪvɫi"],
    ["actual", "thực", "ˈækʃəɫ"],
    ["acute", "cấp", "əkˈjut"],
    ["adaptable", "có khả năng thích ứng rất cao.", "əˈdæptəbəɫ"],
    ["addict", "người nghiện, con nghiện", "ˈæˌdɪkt"],
    ["addicted", "Nghiện", "əˈdɪktɪd"],
    ["addiction", "Nghiện", "əˈdɪkʃən"],
    ["additionally", "Ngoài ra,", "əˈdɪʃəˌnəɫi"],
    ["adequate", "đầy đủ", "ˈædəˌkweɪt"],
    ["adequately", "đầy đủ", "ˈædəkwətɫi"],
    ["adjustment", "điều chỉnh", "əˈdʒəstmənt"],
    ["administrative", "hành", "ədˈmɪnəˌstɹeɪtɪv"],
    ["admirable", "Rất đáng khâm phục.", "ˈædmɝəbəɫ"],
    ["admiringly", "ngưỡng mộ", "ædˈmaɪɹɪŋɫi"],
    ["admittedly", "phải thừa nhận", "ædˈmɪtɪdɫi"],
    ["adopted", "áp dụng", "əˈdɑptɪd"],
    ["adoption", "sự nhận nuôi", "əˈdɑpʃən"],
    ["adore", "ngưỡng mộ", "əˈdɔɹ"],
    ["adorn", "tô điểm", "əˈdɔɹn"],
    ["advance", "tiến bộ", "ədˈvæns"],
    ["advancement", "tiền (người thừa kế) được nhận trước", "ədˈvænsmənt"],
    ["advent", "Mùa Vọng", "ˈædˌvɛnt"],
    ["adventurous", "Mạo hiểm", "ædˈvɛntʃɝəs"],
    ["adverse", "bất lợi", "ˈædˌvɝs"],
    ["adversely", "bất lợi", "ædˈvɝsɫi"],
    ["affectionate", "tình", "əˈfɛkʃənət"],
    ["affectionately", "trìu mến", "əˈfɛkʃənətɫi"],
    ["affordable", "có thể chấp nhận", "əˈfɔɹdəbəɫ"],
    ["ageless", "không tuổi", "ˈeɪdʒɫəs"],
    ["aggressively", "Gây hấn", "əˈɡɹɛsɪvɫi"],
    ["agony", "Nỗi thống khổ...", "ˈæɡəni"],
    ["aircraft", "máy bay", "ˈɛɹˌkɹæft"],
    ["corona", "quầng sáng, điện hoa", "kɝˈoʊnə"],
    ["alcoholism", "tác hại của rượu (đối với cơ thể)", "ˈæɫkəˌhɔˌɫɪzəm"],
    ["alert", "cảnh báo", "əˈɫɝt"],
    ["allegation", "cáo buộc", "ˌæɫəˈɡeɪʃən"],
    ["alliance", "liên minh", "əˈɫaɪəns"],
    ["ally", "đồng minh, liên minh", "ˈæɫaɪ"],
    ["alongside", "sát cạnh, kế bẽn, dọc theo", "əˈɫɔŋˈsaɪd"],
    ["alphabetical", "thuộc bảng chứ cái", "ˌæɫfəˈbɛtɪkəɫ"],
    ["altar", "bàn thờ", "ˈɔɫtɝ"],
    ["alter", "thay đồi, biến đồi, sửa đồi", "ˈɔɫtɝ"],
    ["alternate", "thay phiên", "ˈɔɫtɝˌneɪt"],
    ["alternatively", "một sự lựa chọn", "ɔɫˈtɝnətɪvɫi"],
    ["altitude", "độ cao (so với mặt nước biển)", "ˈæɫtəˌtud"],
    ["amaze", "làm ngạc nhiên, làm sửng sốt", "əˈmeɪz"],
    ["amazingly", "đáng kinh ngạc", "əˈmeɪzɪŋɫi"],
    ["ambassador", "đại sứ", "æmˈbæsədɝ"],
    ["ambiguity", "[sự", "ˌæmbɪɡˈjuəti"],
    ["corporal", "(món) Vật chất.", "ˈkɔɹpɝəɫ"],
    ["amplifier", "bộ khuếch đại", "ˈæmpɫəˌfaɪɝ"],
    ["amplify", "khuếch đại", "ˈæmpɫəˌfaɪ"],
    ["amuse", "làm cho vui, thích, làm buồn cười", "əmˈjuz"],
    ["analogy", "sự tương tự", "əˈnæɫədʒi"],
    ["analyst", "nhà phân tích", "ˈænəɫɪst"],
    ["anchor", "tắc kê", "ˈæŋkɝ"],
    ["anchorage", "chỗ neo thuyền", "ˈæŋkɝədʒ"],
    ["corporate", "công ty", "ˈkɔɹpɝət"],
    ["animate", "Hoạt Họa", "ˈænəˌmeɪt"],
    ["anonymous", "ẩn danh", "əˈnɑnəməs"],
    ["antiaircraft", "phòng không", "ˌæntaɪˈɛɹˌkɹæft"],
    ["antibacterial", "Kháng sinh", "ˌæntibækˈtɪɹiəɫ"],
    ["anticancer", "chống ung thư", "ˌænˌtaɪˈkænsɝ"],
    ["anticipate", "thấy trước, chặn trước, lường trước", "ænˈtɪsəˌpeɪt"],
    ["anticipation", "sự mong đợi", "ænˌtɪsəˈpeɪʃən"],
    ["corporation", "tập đoàn", "ˌkɔɹpɝˈeɪʃən"],
    ["antivirus", "Phần mềm diệt virus", "ˌæntiˈvaɪɹəs"],
    ["apostrophe", "Dấu ngoặc đơn", "əˈpɑstɹəˌfi"],
    ["applicant", "người ứng tuyển", "ˈæpɫɪkənt"],
    ["appreciative", "Đáng khen ngợi?", "əˈpɹiʃiˌeɪtɪv"],
    ["appropriately", "một cách phù hợp", "əˈpɹoʊpɹiɪtɫi"],
    ["approximate", "giống với, giống hệt với", "əˈpɹɑksəˌmeɪt"],
    ["arch", "vòm", "ˈɑɹtʃ"],
    ["arctic", "Bắc Cực", "ˈɑɹktɪk"],
    ["arena", "Đấu trường", "ɝˈinə"],
    ["correct", "chính xác", "kɝˈɛkt"],
    ["arouse", "khơi dậy", "ɝˈaʊz"],
    ["arrogant", "Ngạo mạn", "ˈɛɹəɡənt"],
    ["artery", "động mạch", "ˈɑɹtɝi"],
    ["correctness", "tính chính xác.", "kɝˈɛktnəs"],
    ["artificially", "nhân tạo", "ˌɑɹtəˈfɪʃəɫi"],
    ["correspond", "trao đổi thư từ", "ˌkɔɹəˈspɑnd"],
    ["correspondent", "phóng viên", "ˌkɔɹəˈspɑndənt"],
    ["aspiration", "sự thổi khí", "ˌæspɝˈeɪʃən"],
    ["aspire", "khao khát", "əˈspaɪɹ"],
    ["assault", "tấn công", "əˈsɔɫt"],
    ["assemble", "tập hợp", "əˈsɛmbəɫ"],
    ["assembly", "việc lắp ráp", "əˈsɛmbɫi"],
    ["assess", "đánh giá", "əˈsɛs"],
    ["assessment", "đánh giá", "əˈsɛsmənt"],
    ["assumption", "giả thiết", "əˈsəmpʃən"],
    ["assurance", "sự đảm bảo", "əˈʃʊɹəns"],
    ["assure", "đảm bảo, cam đoan", "əˈʃʊɹ"],
    ["astonish", "kinh ngạc", "əˈstɑnɪʃ"],
    ["astonished", "Kinh ngạc", "əˈstɑnɪʃt"],
    ["astonishing", "Tuyệt vời.", "əˈstɑnɪʃɪŋ"],
    ["astonishment", "sửng sốt", "əˈstɑnɪʃmənt"],
    ["astronomy", "thiên văn học", "əˈstɹɑnəmi"],
    ["athletics", "Điền kinh", "æθˈɫɛtɪks"],
    ["attached", "đính kèm", "əˈtætʃt"],
    ["attainable", "có thể đạt được", "əˈteɪnəbəɫ"],
    ["attainment", "Tình trạng", "əˈteɪnmənt"],
    ["attendance", "sự có mặt, sự tham dự", "əˈtɛndəns"],
    ["attentive", "chu đáo", "əˈtɛntɪv"],
    ["attentively", "chăm chú", "əˈtɛntɪvɫi"],
    ["attractiveness", "Tính hấp dẫn", "əˈtɹæktɪvnəs"],
    ["attribute", "thuộc tính", "ˈætɹəbˌjut"],
    ["atypical", "không điển hình", "ˌeɪˈtɪpɪkəɫ"],
    ["aubergine", "cà tím", "ˈɔbɝˌdʒin"],
    ["audit", "việc kiểm toán", "ˈɔdɪt"],
    ["audition", "thử giọng", "ɑˈdɪʃən"],
    ["authoritative", "Có uy lực", "əˈθɔɹəˌteɪtɪv"],
    ["availability", "có sẵn", "əˌveɪɫəˈbɪɫəti"],
    ["await", "đang chờ", "əˈweɪt"],
    ["awe", "kinh ngạc", "ˈɑ"],
    ["axis", "trục", "ˈæksəs"],
    ["backup", "sao lưu", "ˈbæˌkəp"],
    ["backyard", "Sân sau", "ˈbækˌjɑɹd"],
    ["badge", "huy hiệu", "ˈbædʒ"],
    ["balanced", "cân bằng", "ˈbæɫənst"],
    ["corresponding", "Tương ứng", "ˌkɔɹəˈspɑndɪŋ"],
    ["corridor", "hành lang.", "ˈkɔɹədɝ"],
    ["ballet", "Ba Lê", "bæˈɫeɪ"],
    ["ballot", "rút thăm", "ˈbæɫət"],
    ["ban", "cấm, cấm chỉ", "ˈbæn"],
    ["banker", "nhà cái", "ˈbæŋkɝ"],
    ["bankrupt", "vỡ nợ", "ˈbæŋkɹəpt"],
    ["bankruptcy", "vỡ nợ", "ˈbæŋkɹəpsi"],
    ["barbershop", "Tiệm hớt tóc", "ˈbɑɹbɝˌʃɑp"],
    ["bargain", "sự mặc cả, sự giao kèo mua bán", "ˈbɑɹɡən"],
    ["barley", "lúa đại mạch", "ˈbɑɹɫi"],
    ["barn", "kho chứa", "ˈbɑɹn"],
    ["barometer", "phong vũ biểu thị trường", "bɝˈɑmɪtɝ"],
    ["barren", "thùng gỗ ghép", "ˈbæɹən"],
    ["barrier", "đặt chướng ngại vật", "ˈbæɹiɝ"],
    ["bartender", "lợn thiến", "ˈbɑɹˌtɛndɝ"],
    ["battlefield", "chiến trường", "ˈbætəɫˌfiɫd"],
    ["crease", "Ủi nếp gấp", "ˈkɹis"],
    ["beak", "mỏ chim", "ˈbik"],
    ["beam", "chùm sáng", "ˈbim"],
    ["bearing", "phương hướng", "ˈbɛɹɪŋ"],
    ["beat", "tiếng đập, đánh đập", "ˈbit"],
    ["beautify", "Làm đẹp!", "ˈbjutɪˌfaɪ"],
    ["bellow", "dưới đây", "ˈbɛɫoʊ"],
    ["belongings", "đồ dùng cá nhân", "bɪˈɫɔŋɪŋz"],
    ["bend", "uốn cong", "ˈbɛnd"],
    ["beneficial", "có lợi", "ˌbɛnəˈfɪʃəɫ"],
    ["benevolence", "tính rộng lượng", "bəˈnɛvəɫəns"],
    ["benevolent", "nhân từ.", "bəˈnɛvəɫənt"],
    ["berry", "trứng cá", "ˈbɛɹi"],
    ["bestow", "ban tặng", "bɪˈstoʊ"],
    ["bestseller", "Bán Chạy Nhất", "ˈbɛˈsɛɫɝ"],
    ["betray", "phản bội", "bɪˈtɹeɪ"],
    ["corrupt", "ươn", "kɝˈəpt"],
    ["corruption", "tham nhũng", "kɝˈəpʃən"],
    ["bid", "trả giá", "ˈbɪd"],
    ["bidding", "đặt giá mua", "ˈbɪdɪŋ"],
    ["costly", "tốn kém", "ˈkɑstɫi"],
    ["billion", "tỷ", "ˈbɪɫjən"],
    ["bind", "trói buộc", "ˈbaɪnd"],
    ["bio", "tiểu sử", "ˌbaɪˈoʊ"],
    ["biological", "sinh học", "ˌbaɪəˈɫɑdʒɪkəɫ"],
    ["biotechnology", "công nghệ sinh học", "ˌbaɪoʊˌtɛkˈnɑɫədʒi"],
    ["birdcage", "lồng chim", "ˈbɝdkeɪdʒ"],
    ["birthplace", "Chỗ sinh", "ˈbɝθˌpɫeɪs"],
    ["bitterly", "đắng cay, chua xót", "ˈbɪtɝɫi"],
    ["bizarre", "- Kỳ lạ thật.", "bəˈzɑɹ"],
    ["blade", "lưỡi (dao, kiếm)", "ˈbɫeɪd"],
    ["blast", "phát thanh", "ˈbɫæst"],
    ["blaze", "- Blaze - Vâng.", "ˈbɫeɪz"],
    ["blend", "vật pha trộn", "ˈbɫɛnd"],
    ["blindly", "mù quáng", "ˈbɫaɪndɫi"],
    ["blindness", "Mù", "ˈbɫaɪndnəs"],
    ["blink", "khối, đống, kết cấu", "ˈbɫɪŋk"],
    ["bloodstream", "Hệ tuần hoàn", "ˈbɫədˌstɹim"],
    ["bloody", "đẫm máu", "ˈbɫədi"],
    ["blooming", "Đua Nở", "ˈbɫumɪŋ"],
    ["costume", "y phục", "ˈkɑstum"],
    ["blur", "Làm Nhoè", "ˈbɫɝ"],
    ["cottage", "nhà tranh", "ˈkɑtədʒ"],
    ["boiling", "sự đun sôi", "ˈbɔɪɫɪŋ"],
    ["bolt", "lắp ráp", "ˈboʊɫt"],
    ["bombard", "bắn phá", "bɑmˈbɑɹd"],
    ["counter", "quầy hàng, quầy thu tiền", "ˈkaʊntɝ"],
    ["bony", "nhiều xương", "ˈboʊni"],
    ["bookish", "Sách", "ˈbʊkɪʃ"],
    ["booklet", "tập sách", "ˈbʊkɫɪt"],
    ["boost", "thúc đẩy", "ˈbust"],
    ["creation", "sự sáng tạo", "kɹiˈeɪʃən"],
    ["bossy", "hách dịch", "ˈbɔsi"],
    ["botany", "thực vật học", "ˈbɑtəni"],
    ["bothered", "làm phiền", "ˈbɑðɝd"],
    ["bothersome", "khó chịu", "ˈbɑðɝsəm"],
    ["bottle", "chai, lọ", "ˈbɑtəɫ"],
    ["bounce", "nảy lên", "ˈbaʊns"],
    ["bourbon", "rượu ngô", "ˈbɝbən"],
    ["boxer", "Quyền Anh", "ˈbɑksɝ"],
    ["bracket", "dấu ngoặc (đơn)", "ˈbɹækɪt"],
    ["countryman", "đồng hương", "ˈkəntɹimən"],
    ["creatively", "sáng tạo", "kɹiˈeɪtɪvɫi"],
    ["bravery", "Dũng cảm", "ˈbɹeɪvɝi"],
    ["breakable", "dễ vỡ", "ˈbɹeɪkəbəɫ"],
    ["breakdown", "chia nhỏ", "ˈbɹeɪkˌdaʊn"],
    ["countrywide", "toàn quốc", "ˈkəntɹiˌwaɪd"],
    ["breathtaking", "Hay đấy.", "ˈbɹɛθˌteɪkɪŋ"],
    ["breed", "nuôi dưỡng, giáo dục", "ˈbɹid"],
    ["breezy", "không ổn định", "ˈbɹizi"],
    ["brewery", "nhà máy bia", "ˈbɹuɝi"],
    ["brilliantly", "RỰC RỠ", "ˈbɹɪɫjəntɫi"],
    ["broadband", "băng thông rộng", "ˈbɹɔdˌbænd"],
    ["broadcaster", "Người Phát thanh", "ˈbɹɔdˌkæstɝ"],
    ["broaden", "mở rộng", "ˈbɹɔdən"],
    ["broadly", "rộng rãi", "ˈbɹɔdɫi"],
    ["brochure", "Tài liệu", "bɹoʊˈʃʊɹ"],
    ["browse", "duyệt", "ˈbɹaʊz"],
    ["browser", "bộ trình duyệt", "ˈbɹaʊzɝ"],
    ["bruise", "vất thâm tím", "ˈbɹuz"],
    ["bud", "nảy chồi", "ˈbəd"],
    ["budget", "ngân sách", "ˈbədʒɪt"],
    ["bulimia", "(chứng) ăn vô độ", "bjuˈɫɪmiə"],
    ["bully", "thợ phụ", "ˈbʊɫi"],
    ["bum", "đốt cháy, thắp, nung, thiêu", "ˈbəm"],
    ["creek", "lạch", "ˈkɹik"],
    ["bun", "bao nhân nho", "ˈbən"],
    ["burdensome", "gánh nặng", "ˈbɝdənsəm"],
    ["bureaucracy", "tệ thư lại", "bjʊˈɹɑkɹəsi"],
    ["burglary", "trộm cắp", "ˈbɝɡɫɝi"],
    ["burial", "An táng", "ˈbɛɹiəɫ"],
    ["creepy", "đáng sợ", "ˈkɹipi"],
    ["bustling", "Chó", "ˈbəsəɫɪŋ"],
    ["courtesy", "xã giao.", "ˈkɝtəsi"],
    ["cabinet", "tủ cỏ nhiều ngăn đựng đồ", "ˈkæbənət"],
    ["cable", "dây cáp", "ˈkeɪbəɫ"],
    ["calmly", "yên lặng, êm ả", "ˈkɑɫmɫi"],
    ["coward", "Bọn nhu nhược", "ˈkaʊɝd"],
    ["candidate", "người ứng cử, thí sinh", "ˈkændədeɪt"],
    ["cane", "cây mía", "ˈkeɪn"],
    ["cannonball", "Đạn Đại Bác", "ˈkænənˌbɔɫ"],
    ["canon", "quy tắc", "ˈkænən"],
    ["capability", "khả năng", "ˌkeɪpəˈbɪɫəti"],
    ["caption", "Chú thích ảnh:", "ˈkæpʃən"],
    ["captive", "bị giới hạn", "ˈkæptɪv"],
    ["caravan", "đoàn người vượt sa mạc", "ˈkæɹəˌvæn"],
    ["cowardly", "- Hèn nhát.", "ˈkaʊɝdɫi"],
    ["cardboard", "bìa cứng, các tông", "ˈkɑɹdˌbɔɹd"],
    ["cardigan", "Áo len đan", "ˈkɑɹdɪɡən"],
    ["carefree", "vô tư", "ˈkɛɹˌfɹi"],
    ["caring", "QUAN TÂM", "ˈkɛɹɪŋ"],
    ["carnival", "lễ hội", "ˈkɑɹnəvəɫ"],
    ["carpool", "Chia sẻ chi phí dịch chuyển bằng ô tô", "ˈkɑɹˌpuɫ"],
    ["carve", "chạm khắc", "ˈkɑɹv"],
    ["cascade", "sắp xếp dạng bậc", "kæˈskeɪd"],
    ["cast", "quăng, ném, thả, đánh gục", "ˈkæst"],
    ["casually", "Tình cờ,", "ˈkæʒəwəɫi"],
    ["catalyst", "vật xúc tác", "ˈkætəɫəst"],
    ["catastrophe", "Thảm họa", "kəˈtæstɹəfi"],
    ["catastrophic", "Tình huống ạ.", "ˌkætəˈstɹɑfɪk"],
    ["catchy", "Lừa gạt!", "ˈkæˌtʃi"],
    ["catering", "sự phục vụ ăn", "ˈkeɪtɝɪŋ"],
    ["cathedral", "Nhà thờ chính tòa", "kəˈθidɹəɫ"],
    ["cease", "dừng, ngớt", "ˈsis"],
    ["ceiling", "trần bay", "ˈsiɫɪŋ"],
    ["cellar", "hầm chứa (thức ăn)", "ˈsɛɫɝ"],
    ["crab", "quả táo dại", "ˈkɹæb"],
    ["crew", "phi hành đoàn", "ˈkɹu"],
    ["cemetery", "Nghĩa trang", "ˈsɛməˌtɛɹi"],
    ["centigrade", "thuộc về độ bách phân", "ˈsɛntəˌɡɹeɪd"],
    ["certificate", "chứng chỉ", "sɝˈtɪfɪkət"],
    ["certification", "sự cấp giấy chứng nhận", "ˌsɝtəfəˈkeɪʃən"],
    ["certify", "chứng thực", "ˈsɝtəˌfaɪ"],
    ["chancellor", "Hiệu Trưởng", "ˈtʃænsəɫɝ"],
    ["chaotic", "hỗn loạn", "keɪˈɑtɪk"],
    ["characteristic", "đặc tính", "ˌkɛɹəktɝˈɪstɪk"],
    ["charming", "♪ Duyên Dáng ♪", "ˈtʃɑɹmɪŋ"],
    ["cheat", "lừa đảo", "ˈtʃit"],
    ["checkpoint", "trạm kiểm soát", "ˈtʃɛkˌpɔɪnt"],
    ["cheeky", "xấc láo", "ˈtʃiki"],
    ["cheerfully", "vui vẻ, phấn khởi", "ˈtʃɪɹfəɫi"],
    ["cheerfulness", "Hạnh phúc", "ˈtʃɪɹfəɫnəs"],
    ["chemotherapy", "hóa trị", "ˌkimoʊˈθɛɹəpi"],
    ["cherished", "ấp ủ", "ˈtʃɛɹɪʃt"],
    ["cherry", "quả anh đào", "ˈtʃɛɹi"],
    ["chew", "nhai, ngẫm nghĩ", "ˈtʃu"],
    ["childish", "- Trẻ con à?", "ˈtʃaɪɫdɪʃ"],
    ["chimney", "///", "ˈtʃɪmni"],
    ["chip", "vỏ bào, mảnh vỡ, chỗ sứt, mẻ", "ˈtʃɪp"],
    ["chop", "chặt, đốn", "ˈtʃɑp"],
    ["chunk", "khúc (bánh mì, fomat)", "ˈtʃəŋk"],
    ["circuit", "Mạch", "ˈsɝkət"],
    ["circuitry", "sơ đồ điện", "ˈsɝkətɹi"],
    ["circumstance", "hoàn cảnh, trường hợp, tình huống", "ˈsɝkəmˌstæns"],
    ["citywide", "(Toàn thành phố.)", "ˈsɪtiˌwaɪd"],
    ["clam", "sò", "ˈkɫæm"],
    ["clap", "Vỗ tay!", "ˈkɫæp"],
    ["clarify", "làm rõ", "ˈkɫɛɹəˌfaɪ"],
    ["classic", "cổ điển, kinh điển", "ˈkɫæsɪk"],
    ["classification", "xếp hạng (một con) tàu", "ˌkɫæsəfəˈkeɪʃən"],
    ["clause", "điều khoản (của hợp đồng hay quy định pháp", "ˈkɫɔz"],
    ["clearness", "độ trong suốt", "ˈkɫɪɹnəs"],
    ["clerical", "Văn phòng", "ˈkɫɛɹəkəɫ"],
    ["client", "máy khách", "ˈkɫaɪənt"],
    ["clog", "tắc nghẽn", "ˈkɫɑɡ"],
    ["closure", "độ khép", "ˈkɫoʊʒɝ"],
    ["clothing", "quần áo, y phục", "ˈkɫoʊðɪŋ"],
    ["clumsy", "Gõ rất chậm.", "ˈkɫəmzi"],
    ["coach", "huấn luyện viên", "ˈkoʊtʃ"],
    ["coaching", "huấn luyện", "ˈkoʊtʃɪŋ"],
    ["coalition", "liên minh", "ˌkoʊəˈɫɪʃən"],
    ["coarse", "thô ráp", "ˈkɔɹs"],
    ["coastline", "Bờ biển", "ˈkoʊstˌɫaɪn"],
    ["cocktail", "rượu cốc-tai", "ˈkɑkˌteɪɫ"],
    ["cocoa", "nước cacao", "ˈkoʊkoʊ"],
    ["coconut", "dừa", "ˈkoʊkəˌnət"],
    ["coherence", "T&#237", "koʊˈhɪɹəns"],
    ["coherent", "mạch lạc", "koʊˈhɪɹənt"],
    ["coincide", "trùng nhau", "ˌkoʊɪnˈsaɪd"],
    ["coincidence", "sự trùng", "koʊˈɪnsɪdəns"],
    ["colleague", "bạn đồng nghiệp", "ˈkɑɫiɡ"],
    ["collector", "thiết bị thu", "kəˈɫɛktɝ"],
    ["colon", "kết tràng", "ˈkoʊɫən"],
    ["colonial", "thuộc địa", "kəˈɫoʊniəɫ"],
    ["coma", "Hôn mê", "ˈkoʊmə"],
    ["comb", "lược", "ˈkoʊm"],
    ["comfortably", "dễ chịu, thoải mái, tiện nghi, ấm củng", "ˈkəmfɝtəbɫi"],
    ["commander", "chỉ huy", "kəˈmændɝ"],
    ["commemorate", "kỷ niệm", "kəˈmɛmɝˌeɪt"],
    ["commerce", "thương mại", "ˈkɑmɝs"],
    ["crack", "nứt nẻ, rạn nứt", "ˈkɹæk"],
    ["commonwealth", "\"Commonwealth\" có thể chỉ một hiệp hội hoặc", "ˈkɑmənˌwɛɫθ"],
    ["communicative", "Hay chuyện trò", "kəmˈjunəkətɪv"],
    ["craftsman", "Nghệ An.", "ˈkɹæfsmən"],
    ["commute", "Đi Lại", "kəmˈjut"],
    ["criminal", "Hình sự", "ˈkɹɪmənəɫ"],
    ["compassionate", "từ bi.", "kəmˈpæʃənət"],
    ["compatible", "hỗ trợ", "kəmˈpætəbəɫ"],
    ["compensate", "bù lại", "ˈkɑmpənˌseɪt"],
    ["compensation", "/ Bù trừ nhiệt độ vỏ", "ˌkɑmpənˈseɪʃən"],
    ["competence", "năng lực", "ˈkɑmpətɪns"],
    ["competent", "khả biến", "ˈkɑmpətɪnt"],
    ["compile", "sưu tầm tài liệu", "kəmˈpaɪɫ"],
    ["completion", "sự làm xong", "kəmˈpɫiʃən"],
    ["crater", "máy cho chai vào thùng", "ˈkɹeɪtɝ"],
    ["complexity", "biến động", "kəmˈpɫɛksəti"],
    ["component", "Cấu kiện", "kəmˈpoʊnənt"],
    ["comprehension", "sự hiểu", "ˌkɑmpɹiˈhɛnʃən"],
    ["compress", "nén, ép chặt lại", "ˈkɑmpɹɛs"],
    ["compression", "nén", "kəmˈpɹɛʃən"],
    ["compulsory", "cưỡng bách", "kəmˈpəɫsɝi"],
    ["compute", "tính toán", "kəmˈpjut"],
    ["conceal", "giấu giếm", "kənˈsiɫ"],
    ["concede", "Nhường", "kənˈsid"],
    ["conceit", "tính tự cao tự đại", "kənˈsit"],
    ["conceivable", "có thể hình dung được", "kənˈsivəbəɫ"],
    ["conceive", "Thụ tinh", "kənˈsiv"],
    ["conception", "quan niệm", "kənˈsɛpʃən"],
    ["concern", "liên quan", "kənˈsɝn"],
    ["concerning", "bâng khuâng, ái ngại", "kənˈsɝnɪŋ"],
    ["concession", "tô giới", "kənˈsɛʃən"],
    ["concrete", "bê tông", "ˈkɑnkɹit"],
    ["condemn", "thải đi", "kənˈdɛm"],
    ["cone", "nón", "ˈkoʊn"],
    ["conference", "hội nghị", "ˈkɑnfɝəns"],
    ["conferencing", "hội nghị trực tuyến,", "ˈkɑnfɹənsɪŋ"],
    ["confess", "- Thú tội đi.", "kənˈfɛs"],
    ["confession", "tỏ tình", "kənˈfɛʃən"],
    ["confidently", "tự tin", "ˈkɑnfədəntɫi"],
    ["confront", "đối mặt, đối diện", "kənˈfɹənt"],
    ["conjunction", "sự liên hợp", "kənˈdʒəŋkʃən"],
    ["conquest", "Sự chinh phục", "ˈkɑŋkwɛst"],
    ["conscience", "Lương tâm", "ˈkɑnʃəns"],
    ["consciousness", "ý thức", "ˈkɑnʃəsnəs"],
    ["consensus", "đồng thuận", "kənˈsɛnsəs"],
    ["consent", "sự chấp thuận", "kənˈsɛnt"],
    ["considerably", "đáng kế, lớn lao", "kənˈsɪdɝəbɫi"],
    ["considering", "Xét cho cùng...", "kənˈsɪdɝɪŋ"],
    ["consistent", "nhất quán", "kənˈsɪstənt"],
    ["consolation", "Khuyến khích:", "ˌkɑnsəˈɫeɪʃən"],
    ["console", "Bảng điều khiển", "ˈkɑnsoʊɫ"],
    ["constant", "kiên trì, bển lòng", "ˈkɑnstənt"],
    ["consult", "tra cứu, tham khảo", "kənˈsəɫt"],
    ["consultant", "tư vấn", "kənˈsəɫtənt"],
    ["contaminate", "nhiễm", "kənˈtæməˌneɪt"],
    ["contemporary", "đương thời, đương đại", "kənˈtɛmpɝˌɛɹi"],
    ["contempt", "sự coi thường", "kənˈtɛmpt"],
    ["content", "nội dung", "ˈkɑntɛnt"],
    ["contract", "hợp đồng", "ˈkɑnˌtɹækt"],
    ["contradict", "TIẾP TỤC", "ˌkɑntɹəˈdɪkt"],
    ["contradiction", "- Mâu thuẫn?", "ˌkɑntɹəˈdɪkʃən"],
    ["contradictory", "mâu thuẫn", "ˌkɑntɹəˈdɪktɝi"],
    ["controversy", "tranh cãi", "ˈkɑntɹəˌvɝsi"],
    ["conveniently", "Tiện thật.", "kənˈvinjəntɫi"],
    ["convention", "hội nghị, hiệp định, quy ước", "kənˈvɛnʃən"],
    ["conventional", "quy ước", "kənˈvɛnʃənəɫ"],
    ["crawl", "thu thập thông tin", "ˈkɹɔɫ"],
    ["conversely", "Ngược lại.", "ˈkɑnvɝsɫi"],
    ["conversion", "sự trao đổi", "kənˈvɝʒən"],
    ["convert", "chuyển đổi", "ˈkɑnvɝt"],
    ["convinced", "Chắc chắn!", "kənˈvɪnst"],
    ["cool", "ngầu", "ˈkuɫ"],
    ["cooperate", "///", "ˈkwɑpɝˌeɪt"],
    ["cooperation", "sự hợp tác", "ˌkwɑpɝˈeɪʃən"],
    ["cooperative", "hợp tác", "koʊˈɑpɝˌeɪtɪv"],
    ["cope", "đối phó, đương đầu", "ˈkoʊp"],
    ["copper", "thùng nấu xà phòng", "ˈkɑpɝ"],
    ["coral", "tóc ngôcolor", "ˈkɔɹəɫ"],
  ],
  "C1": [
    ["sophisticated", "tinh vi, phức tạp", "səˈfɪstəˌkeɪtɪd"],
    ["inevitable", "không thể tránh khỏi", "ˌɪˈnɛvətəbəɫ"],
    ["ambiguous", "mơ hồ", "æmˈbɪɡjuəs"],
    ["comprehensive", "toàn diện", "ˌkɑmpɹiˈhɛnsɪv"],
    ["deteriorate", "xấu đi", "dɪˈtɪɹiɝˌeɪt"],
    ["reluctant", "miễn cưỡng", "ɹiˈɫəktənt"],
    ["substantial", "đáng kể", "səbˈstænʃəɫ"],
    ["controversial", "gây tranh cãi", "ˌkɑntɹəˈvɝʃəɫ"],
    ["meticulous", "tỉ mỉ", "məˈtɪkjəɫəs"],
    ["put up with", "chịu đựng", "ˈpʊt ˈəp ˈwɪð"],
    ["come up with", "nghĩ ra", "ˈkəm ˈəp ˈwɪð"],
    ["plausible", "có vẻ hợp lý", "ˈpɫɔzəbəɫ"],
    ["flee", "chạy trốn", "ˈfɫi"],
    ["fairness", "công bằng", "ˈfɛɹnəs"],
    ["ironic", "rái cá", "aɪˈɹɑnɪk"],
    ["proceeds", "tiền thu được", "pɹəˈsidz"],
    ["logic", "lô gic", "ˈɫɑdʒɪk"],
    ["well", "giỏi", "ˈwɛɫ"],
    ["memoir", "bút ký", "ˈmɛmˌwɑɹ"],
    ["scattered", "manh mún", "ˈskætɝd"],
    ["suburban", "giao, Dương Tuyền", "səˈbɝbən"],
    ["ritual", "nghi lễ", "ˈɹɪtʃuəɫ"],
    ["cater", "phục vụ theo yêu cầu", "ˈkeɪtɝ"],
    ["seal", "hải cầu", "ˈsiɫ"],
    ["gross", "tổng", "ˈɡɹoʊs"],
    ["minimal", "tối thiểu", "ˈmɪnəməɫ"],
    ["prospective", "tiến cứu", "pɹəˈspɛktɪv"],
    ["presently", "hiện tại", "ˈpɹɛzəntɫi"],
    ["inmate", "tù nhân", "ˈɪnˌmeɪt"],
    ["beloved", "người yêu dấu", "bɪˈɫəvd"],
    ["assert", "khẳng định", "əˈsɝt"],
    ["warfare", "chiến tranh", "ˈwɔɹˌfɛɹ"],
    ["whatsoever", "bất cứ chuyện gì", "ˌhwətsoʊˈɛvɝ"],
    ["forthcoming", "sap toi", "ˈfɔɹθˈkəmɪŋ"],
    ["contemplate", "ngắm thành phố về đêm", "ˈkɑntəmˌpɫeɪt"],
    ["desktop", "mặt bàn giấy", "ˈdɛskˌtɑp"],
    ["sheer", "da cừu", "ˈʃɪɹ"],
    ["withdrawal", "triệt tiêu", "wɪðˈdɹɔəɫ"],
    ["motorist", "người lái xe máy", "ˈmoʊtɝɪst"],
    ["toll", "tổn thất", "ˈtoʊɫ"],
    ["peculiar", "biệt", "pəkˈjuɫjɝ"],
    ["variable", "biến đổi", "ˈvɛɹiəbəɫ"],
    ["villager", "dân làng", "ˈvɪɫɪdʒɝ"],
    ["span", "nhịp", "ˈspæn"],
    ["trophy", "chiến lợi phẩm", "ˈtɹoʊfi"],
    ["damaging", "có hại, hại", "ˈdæmɪdʒɪŋ"],
    ["overly", "quá mức", "ˈoʊvɝɫi"],
    ["correlation", "sự tương quan", "ˌkɔɹəˈɫeɪʃən"],
    ["dimension", "kích thước", "dɪˈmɛnʃən"],
    ["vulnerability", "lỗ hổng", "ˌvəɫnɝəˈbɪɫɪti"],
    ["magnetic", "từ tính", "mæɡˈnɛtɪk"],
    ["accumulation", "ứ đọng", "əkˌjumjəˈɫeɪʃən"],
    ["quota", "chỉ tiêu", "ˈkwoʊtə"],
    ["parameter", "thông số", "pɝˈæmətɝ"],
    ["contrary", "trái ngược", "ˈkɑntɹɛɹi"],
    ["motive", "động cơ", "ˈmoʊtɪv"],
    ["prejudice", "gây tổn hại?", "ˈpɹɛdʒədɪs"],
    ["occurrence", "lần xuất hiện", "əˈkɝəns"],
    ["productivity", "hiệu suất", "ˌpɹoʊdəkˈtɪvəti"],
    ["destructive", "phá hoại", "dɪˈstɹəktɪv"],
    ["gallon", "galon", "ˈɡæɫən"],
    ["capitalism", "sự tập trung tư bản (trong tay thiểu số)", "ˈkæpɪtəˌɫɪzəm"],
    ["transparency", "tính minh bạch", "tɹænˈspɛɹənsi"],
    ["implementation", "thực thi", "ˌɪmpɫəmɛnˈteɪʃən"],
    ["administer", "quản lý", "ədˈmɪnəstɝ"],
    ["seize", "nắm bắt", "ˈsiz"],
    ["upcoming", "sắp diễn ra", "ˈəpˌkəmɪŋ"],
    ["feminist", "chủ nghĩa nam nữ bình quyền", "ˈfɛmənɪst"],
    ["influential", "có ảnh hưởng sao?", "ˌɪnfɫuˈɛnʃəɫ"],
    ["sphere", "hình cầu", "ˈsfɪɹ"],
    ["prevention", "sự ngăn cản", "pɹiˈvɛnʃən"],
    ["assassination", "ám sát", "əˌsæsəˈneɪʃən"],
    ["harassment", "quấy rối", "hɝˈæsmənt"],
    ["devil", "thịt rán quá lửa", "ˈdɛvəɫ"],
    ["versus", "đấu với", "ˈvɝsəs"],
    ["embark", "lên tàu", "ɛmˈbɑɹk"],
    ["inadequate", "không thích hợp", "ˌɪˈnædəˌkweɪt"],
    ["stun", "làm choáng váng (súc vật trước khi mổ)", "ˈstən"],
    ["correspondence", "thư từ qua lại", "ˌkɔɹəˈspɑndəns"],
    ["abound", "có rất nhiều", "əˈbaʊnd"],
    ["abstraction", "Sự trừu tượng", "æbˈstɹækʃən"],
    ["intuition", "Trực giác", "ˌɪntuˈɪʃən"],
    ["acidic", "có tính chất axit", "əˈsɪdɪk"],
    ["acoustic", "âm thanh", "əˈkustɪk"],
    ["acoustically", "âm học", "əˈkustɪkɫi"],
    ["acoustics", "âm học", "əˈkustɪks"],
    ["intuitive", "TRỰC QUAN", "ˌɪnˈtuətɪv"],
    ["acutely", "một cách sâu sắc", "əkˈjutɫi"],
    ["adjoin", "kề, nối", "əˈdʒɔɪn"],
    ["adjoining", "liền kề", "əˈdʒɔɪnɪŋ"],
    ["adjustable", "điều chỉnh được", "əˈdʒəstəbəɫ"],
    ["intuitively", "bằng trực giác", "ˌɪnˈtuɪtɪvɫi"],
    ["advantageous", "thuận lợi.", "ˌædvənˈteɪdʒəs"],
    ["adversary", "đối thủ", "ˈædvɝˌsɛɹi"],
    ["advisory", "TƯ VẤN", "ædˈvaɪzɝi"],
    ["aesthetic", "thẩm mỹ công trình", "ɛsˈθɛtɪk"],
    ["aesthetically", "Mỹ học", "ɛsˈθɛtɪkɫi"],
    ["agonize", "đau đớn", "ˈæɡəˌnaɪz"],
    ["agreeable", "dễ chịu", "əˈɡɹiəbəɫ"],
    ["aimless", "không mục đích", "ˈeɪmɫəs"],
    ["aimlessly", "không mục đích", "ˈeɪmɫəsɫi"],
    ["alienate", "chuyển nhượng (tài sản...)", "ˈeɪɫjəˌneɪt"],
    ["align", "Căn dòng", "əˈɫaɪn"],
    ["alignment", "sự liên kết", "əˈɫaɪnmənt"],
    ["allege", "cáo buộc", "əˈɫɛdʒ"],
    ["alleviate", "giảm nhẹ", "əˈɫiviˌeɪt"],
    ["altruism", "tập tính tha mồi", "ˈæɫtɹuˌɪzəm"],
    ["altruistic", "Sự vị tha", "ˌɔɫtɹuˈɪstɪk"],
    ["amateur", "nghiệp dư", "ˈæməˌtɝ"],
    ["amid", "Diyarbakır", "əˈmɪd"],
    ["amplification", "(sự) nhân bội, sao chép ra nhiều bản", "ˌæmpɫəfəˈkeɪʃən"],
    ["amply", "đủ", "ˈæmpɫi"],
    ["anchored", "Neo Chốt (Anchored)", "ˈæŋkɝd"],
    ["anthropologist", "Nhà nhân chủng học", "ˌænθɹəˈpɑɫədʒəst"],
    ["anthropology", "tâm lý học", "ˌænθɹəˈpɑɫədʒi"],
    ["anticlimactic", "phản đối khí hậu", "ˌæntikɫaɪˈmæktɪk"],
    ["antics", "trò hề", "ˈæntɪks"],
    ["antiquated", "lỗi thời", "ˈæntəˌkweɪtɪd"],
    ["antiquity", "Thời cổ đại", "ænˈtɪkwəti"],
    ["appalling", "kinh khủng", "əˈpɔɫɪŋ"],
    ["appallingly", "kinh khủng", "əˈpɔɫɪŋɫi"],
    ["appliance", "thiết bị gia dụng", "əˈpɫaɪəns"],
    ["apprehensive", "E ngại?", "ˌæpɹiˈhɛnsɪv"],
    ["apprentice", "người tập sự", "əˈpɹɛntəs"],
    ["apprenticeship", "Học việc", "əˈpɹɛntəsˌʃɪp"],
    ["invoice", "hóa đơn", "ˈɪnvɔɪs"],
    ["irate", "chọc tức, quấy rầy, kích thích", "aɪˈɹeɪt"],
    ["aquarium", "Bể thủy sinh", "əˈkwɛɹiəm"],
    ["artistically", "nghệ thuật", "ɑɹˈtɪstɪkɫi"],
    ["assertion", "sự khẳng định, điều quyết đoán", "əˈsɝʃən"],
    ["astray", "Lạc về", "əˈstɹeɪ"],
    ["atmospheric", "Khí quyển", "ˌætməsˈfɛɹɪk"],
    ["automatic", "sử dụng", "ˌɔtəˈmætɪk"],
    ["automatically", "tự động", "ˌɔtəˈmætɪkɫi"],
    ["irony", "Đúng là trớ trêu thật.", "ˈaɪɹəni"],
    ["baldly", "hói đầu", "ˈbɔɫdɫi"],
    ["batter", "sườn dốc", "ˈbætɝ"],
    ["battered", "bị đánh đập", "ˈbætɝd"],
    ["isolate", "tách ra", "ˈaɪsəˌɫeɪt"],
    ["bearded", "Râu", "ˈbɪɹdəd"],
    ["beforehand", "Tới trước.", "bɪˈfɔɹˌhænd"],
    ["beguiling", "quyến rũ", "bɪˈɡaɪɫɪŋ"],
    ["behind", "sau, ở đằng sau", "bɪˈhaɪnd"],
    ["isolated", "Đã tách", "ˈaɪsəˌɫeɪtəd"],
    ["benignly", "lành tính", "bəˈnaɪnɫi"],
    ["bequeath", "để lại", "bɪˈkwiθ"],
    ["itinerary", "lộ trình", "aɪˈtɪnɝˌɛɹi"],
    ["bliss", "hạnh phúc trọn vẹn", "ˈbɫɪs"],
    ["blister", "sự sinh bọt", "ˈbɫɪstɝ"],
    ["blithely", "Hoàn toàn ..", "ˈbɫaɪθɫi"],
    ["blockbuster", "bom tấn", "ˈbɫɑkˌbəstɝ"],
    ["bloom", "nở rộ", "ˈbɫum"],
    ["bouquet", "hương vị", "buˈkeɪ"],
    ["brainwash", "tẩy não", "ˈbɹeɪnˌwɑʃ"],
    ["brainwashing", "tẩy não", "ˈbɹeɪnˌwɑʃɪŋ"],
    ["bribe", "vật hối lộ", "ˈbɹaɪb"],
    ["bribery", "tội hối lộ", "ˈbɹaɪbɝi"],
    ["bubbly", "sủi bọt", "ˈbəbəɫi"],
    ["buffer", "dung dịch đệm", "ˈbəfɝ"],
    ["buffoon", "trâu", "bəˈfun"],
    ["bulk", "xếp thành đống", "ˈbəɫk"],
    ["bulky", "to lớn", "ˈbəɫki"],
    ["bureaucratic", "tính chất quan liêu", "ˌbjʊɹəˈkɹætɪk"],
    ["buzzer", "Chuông báo", "ˈbəzɝ"],
    ["bypass", "đường vòng", "ˈbaɪˌpæs"],
    ["calorie", "Ca-lo", "ˈkæɫɝi"],
    ["candid", "thẳng thắn", "ˈkændəd"],
    ["jersey", "Trang phục", "ˈdʒɝzi"],
    ["canoe", "Chèo thuyền mái chèo đơn (canoe)", "kəˈnu"],
    ["carpenter", "Thợ mộc", "ˈkɑɹpəntɝ"],
    ["carpentry", "Thợ mộc", "ˈkɑɹpəntɹi"],
    ["carrier", "đơn vị vận chuyển", "ˈkæɹiɝ"],
    ["cavity", "lỗ hổng", "ˈkævəti"],
    ["ceaseless", "không ngừng nghỉ", "ˈsisɫɪs"],
    ["ceaselessly", "không ngừng", "ˈsizɫəsɫi"],
    ["cessation", "chấm dứt", "ˌsɛˈseɪʃən"],
    ["chart", "đồ thị", "ˈtʃɑɹt"],
    ["charter", "thuê", "ˈtʃɑɹtɝ"],
    ["chill", "sự làm lạnh", "ˈtʃɪɫ"],
    ["chilly", "lạnh", "ˈtʃɪɫi"],
    ["chisel", "sự đục", "ˈtʃɪzəɫ"],
    ["churn", "thùng đựng kem", "ˈtʃɝn"],
    ["circulate", "tuần hoàn", "ˈsɝkjəˌɫeɪt"],
    ["circulation", "sự lưu thông", "ˈsɝkjəˌɫeɪʃən"],
    ["citation", "Trích Dẫn", "saɪˈteɪʃən"],
    ["cite", "dẫn chứng", "ˈsaɪt"],
    ["clammy", "ẩm ướt", "ˈkɫæmi"],
    ["clan", "Thị tộc", "ˈkɫæn"],
    ["class", "hạng", "ˈkɫæs"],
    ["classy", "Cao cấp đấy.", "ˈkɫæsi"],
    ["claustrophobia", "Chứng sợ không gian hẹp", "ˌkɫɔstɹəˈfoʊbiə"],
    ["claustrophobic", "Chứng sợ không gian hẹp", "ˌkɫɔstɹəˈfoʊbɪk"],
    ["cleanly", "sạch sẽ", "ˈkɫinɫi"],
    ["clench", "nắm chặt lại", "ˈkɫɛntʃ"],
    ["cleverness", "Lanh lợi, thông minh.", "ˈkɫɛvɝnəs"],
    ["climactic", "cao trào", "kɫaɪˈmæktɪk"],
    ["climax", "cao điểm, cao trào", "ˈkɫaɪˌmæks"],
    ["clinical", "lâm sàng", "ˈkɫɪnəkəɫ"],
    ["cloak", "Áo choàng.", "ˈkɫoʊk"],
    ["closeness", "sự gần gũi", "ˈkɫoʊsnɪs"],
    ["clutch", "Máy công cụ điều khiển số", "ˈkɫətʃ"],
    ["clutter", "thời gian quảng cáo thương mại", "ˈkɫətɝ"],
    ["collaborate", "Cộng tác", "kəˈɫæbɝˌeɪt"],
    ["collaboration", "sự cộng tác", "kəˌɫæbɝˈeɪʃən"],
    ["collaborative", "Hợp tác", "kəˈɫæbɝˌeɪtɪv"],
    ["collaborator", "cộng tác viên", "kəˈɫæbɝˌeɪtɝ"],
    ["commend", "khen thưởng", "kəˈmɛnd"],
    ["commendation", "Khen thưởng", "ˌkɑmənˈdeɪʃən"],
    ["commercially", "thương mại", "kəˈmɝʃəɫi"],
    ["compel", "ép buộc", "kəmˈpɛɫ"],
    ["complementary", "bù", "ˌkɑmpɫəˈmɛntɹi"],
    ["compliance", "sự phù hợp với", "kəmˈpɫaɪəns"],
    ["compliant", "tuân thủ", "kəmˈpɫaɪənt"],
    ["complimentary", "sự biếu", "ˌkɑmpɫəˈmɛntɝi"],
    ["comply", "tuân theo", "kəmˈpɫaɪ"],
    ["comprise", "BAO GỒM", "kəmˈpɹaɪz"],
    ["compromised", "Phân Trộn", "ˈkɑmpɹəˌmaɪzd"],
    ["compulsion", "(sự) cưỡng bức", "kəmˈpəɫʃən"],
    ["jurisdiction", "Quyền lực pháp lý", "ˌdʒʊɹəsˈdɪkʃən"],
    ["justly", "công bằng", "ˈdʒəstɫi"],
    ["concur", "Dạ...", "kənˈkɝ"],
    ["condition", "điểu kiện", "kənˈdɪʃən"],
    ["conditional", "điều kiệnStencils", "kənˈdɪʃənəɫ"],
    ["conditionally", "Có điều kiện.", "kənˈdɪʃənəɫi"],
    ["confide", "Bảo mật", "kənˈfaɪd"],
    ["confinement", "sự giam cầm", "kənˈfaɪnmənt"],
    ["conform", "tuân thủ", "kənˈfɔɹm"],
    ["conformity", "sự chỉnh hợp", "kənˈfɔɹməti"],
    ["congregate", "tụ tập", "ˈkɑŋɡɹəˌɡeɪt"],
    ["conjure", "liên tưởng", "ˈkɑndʒɝ"],
    ["connoisseur", "người sành sỏi", "ˌkɑnəˈsɝ"],
    ["conscientious", "Có lương tâm", "ˌkɑnʃiˈɛnʃəs"],
    ["conscientiously", "tận tâm", "ˌkɑntʃiˈɛntʃəsɫi"],
    ["conservatory", "phòng ấm (để ươm cây)", "kənˈsɝvətɔɹi"],
    ["conserve", "sự trữ", "kənˈsɝv"],
    ["constraint", "sự ràng buộc, sự hạn chế", "kənˈstɹeɪnt"],
    ["consultancy", "Tư vấn", "kənˈsəɫtənsi"],
    ["consultation", "sự cố vấn", "ˌkɑnsəɫˈteɪʃən"],
    ["contest", "cuộc thi, trận đấu", "ˈkɑntɛst"],
    ["contested", "Tranh cãi", "kənˈtɛstəd"],
    ["contextual", "Ngữ cảnh", "ˌkɑnˈtɛksˌtʃuəɫ"],
    ["continuity", "tính liên tục", "ˌkɑntəˈnuəti"],
    ["contractor", "nhà đấu thầu", "ˈkɑnˌtɹæktɝ"],
    ["convict", "người bị kết án", "ˈkɑnvɪkt"],
    ["conviction", "lòng tin chắc, sự kết án, phán quyết", "kənˈvɪkʃən"],
    ["convoluted", "phức tạp", "ˈkɑnvəˌɫutəd"],
    ["corps", "đoàn", "ˈkɔɹ"],
    ["coupled", "được ghép nối", "ˈkəpəɫd"],
    ["coverage", "phủ sóng", "ˈkəvɝədʒ"],
    ["crave", "thèm", "ˈkɹeɪv"],
    ["craving", "Thèm", "ˈkɹeɪvɪŋ"],
    ["creamy", "thuộc kem", "ˈkɹimi"],
    ["credential", "THÔNG TIN XÁC THỰC", "kɹəˈdɛnʃəɫ"],
    ["credibility", "tín nhiệm", "ˌkɹɛdəˈbɪɫɪti"],
    ["credible", "tin được", "ˈkɹɛdəbəɫ"],
    ["credibly", "đáng tin cậy", "ˈkɹɛdəbɫi"],
    ["juvenile", "-Mất đầu nè !", "ˈdʒuvəˌnaɪɫ"],
    ["crude", "dầu mỏ", "ˈkɹud"],
    ["crudely", "thô lỗ", "ˈkɹudɫi"],
    ["crumb", "tán", "ˈkɹəm"],
    ["crumble", "vỡ vụn", "ˈkɹəmbəɫ"],
    ["customary", "Theo phong tục, tập quán.", "ˈkəstəˌmɛɹi"],
    ["cynic", "Thợ C¬ khÝ", "ˈsɪnɪk"],
    ["cynical", "Hoài nghi", "ˈsɪnɪkəɫ"],
    ["cynically", "hoài nghi", "ˈsɪnɪkəɫi"],
    ["cynicism", "Sự hoài nghi", "ˈsɪnɪˌsɪzəm"],
    ["darkroom", "phòng tối", "ˈdɑɹˌkɹum"],
    ["landscape", "phong cảnh", "ˈɫænˌskeɪp"],
    ["daunting", "nản chí", "ˈdɔntɪŋ"],
    ["daydream", "mơ mộng hão huyền", "ˈdeɪˌdɹim"],
    ["debut", "Ra mắt", "ˈdeɪbju"],
    ["deceit", "sự lừa dối", "dəˈsit"],
    ["degradation", "sự thóai hóa", "ˌdɛɡɹəˈdeɪʃən"],
    ["degrade", "Xuống cấp", "dɪˈɡɹeɪd"],
    ["degrading", "xuống cấp", "dɪˈɡɹeɪdɪŋ"],
    ["demise", "qua đời", "dɪˈmaɪz"],
    ["demo", "bản demo", "ˈdɛmoʊ"],
    ["demographic", "Nhân khẩu học", "ˌdɛməˈɡɹæfɪk"],
    ["demographically", "về mặt nhân khẩu học", "ˌdɛməˈɡɹæfɪkɫi"],
    ["demography", "nhân khẩu học", "dɪˈmɑɡɹəfi"],
    ["demolition", "Phá dỡ", "ˌdɛməˈɫɪʃən"],
    ["depict", "miêu tả", "dɪˈpɪkt"],
    ["depiction", "miêu tả", "dɪˈpɪkʃən"],
    ["deprivation", "Thiếu thốn", "ˌdɛpɹəˈveɪʃən"],
    ["descent", "hậu duệ", "dɪˈsɛnt"],
    ["desert", "sa mạc", "ˈdɛzɝt"],
    ["desertion", "Đào ngũ", "dɪˈzɝʃən"],
    ["detest", "ghê tởm", "diˈtɛst"],
    ["detriment", "thiệt hại", "ˈdɛtɹəmənt"],
    ["detrimental", "Bất lợi", "ˌdɛtɹəˈmɛnəɫ"],
    ["detritus", "mảnh vụn vỡ", "ˈdɛtɹətəs"],
    ["devotee", "tín đồ", "ˌdɛvəˈti"],
    ["lapse", "thất hiệu", "ˈɫæps"],
    ["discourse", "đàm luận", "ˈdɪskɔɹs"],
    ["disdain", "khinh thị", "dɪsˈdeɪn"],
    ["disillusionment", "vỡ mộng", "ˌdɪsɪˈɫuʒənmənt"],
    ["dislodge", "tháo khuôn", "dɪˈsɫɑdʒ"],
    ["dismal", "ảm đạm", "ˈdɪzməɫ"],
    ["dismally", "ảm đạm", "ˈdɪzməɫi"],
    ["dismay", "mất tinh thần", "dɪsˈmeɪ"],
    ["dispensary", "phòng khám và phát thuốc", "ˈdɪspɛnˌsɛɹi"],
    ["dispense", "Phân chia", "dɪˈspɛns"],
    ["disquieting", "không yên tâm", "dɪsˈkwaɪətɪŋ"],
    ["dissect", "mổ xẻ", "daɪˈsɛkt"],
    ["dissection", "Phân tách", "ˈdaɪsɛkʃən"],
    ["dither", "Pha Trộn Điểm Ảnh (Dither)", "ˈdɪðɝ"],
    ["diverge", "phân kỳ", "dɪˈvɝdʒ"],
    ["divergence", "sự phân kỳ", "daɪˈvɝdʒəns"],
    ["divergent", "Dị Biệt.", "daɪˈvɝdʒənt"],
    ["diversity", "đa dạng", "daɪˈvɝsɪti"],
    ["docile", "ngoan ngoãn", "ˈdɑsəɫ"],
    ["domestically", "trong nước", "dəˈmɛstɪkɫi"],
    ["domesticate", "thuần hóa", "dəˈmɛstəˌkeɪt"],
    ["domestication", "Thuần hóa", "dəˌmɛstəˈkeɪʃən"],
    ["dominant", "trội", "ˈdɑmənənt"],
    ["domination", "vượt trội", "ˌdɑməˈneɪʃən"],
    ["dramatist", "nhà soạn kịch", "ˈdɹɑmətɪst"],
    ["drawback", "Nhược điểm", "ˈdɹɔˌbæk"],
    ["drill", "máy khoan", "ˈdɹɪɫ"],
    ["drive", "lái, đua xe", "ˈdɹaɪv"],
    ["durable", "Lâu bền", "ˈdʊɹəbəɫ"],
    ["lavatory", "nhà vệ sinh", "ˈɫævəˌtɔɹi"],
    ["dutiful", "có trách nhiệm", "ˈdutifəɫ"],
    ["dutifully", "chu đáo", "ˈdutifəɫi"],
    ["dynamically", "(Cộng dồn", "daɪˈnæmɪˌkɫi"],
    ["eccentric", "bánh lệch tâm", "ˌɛkˈsɛntɹɪk"],
    ["eclectic", "chiết trung", "ɪˈkɫɛktɪk"],
    ["ecstatically", "ngây ngất", "ɛkˈstætɪkɫi"],
    ["legacy", "di sản", "ˈɫɛɡəsi"],
    ["ego", "cái tôi", "ˈiɡoʊ"],
    ["elaborate", "tỉ mỉ", "ɪˈɫæbɝˌeɪt"],
    ["elaboration", "tỉ mỉ", "ɪˌɫæbɝˈeɪʃən"],
    ["elastic", "co giãn", "ɪˈɫæstɪk"],
    ["lethargic", "Thụ động", "ɫəˈθɑɹdʒɪk"],
    ["elevation", "Độ Nâng", "ˌɛɫəˈveɪʃən"],
    ["lethargy", "thờ ơ", "ˈɫɛθɝdʒi"],
    ["elongate", "Kéo dài ra", "ɪˈɫɔŋɡeɪt"],
    ["elude", "lẩn trốn", "ɪˈɫud"],
    ["elusive", "khó nắm bắt", "ɪˈɫusɪv"],
    ["endorsement", "sự ưng thuận", "ɛnˈdɔɹsmənt"],
    ["engineer", "kỹ sư", "ˈɛndʒəˈnɪɹ"],
    ["engross", "choán chỗ", "ɪnˈɡɹoʊs"],
    ["engrossing", "mê mải", "ɪnˈɡɹoʊsɪŋ"],
    ["enormously", "Vô cùng, hết sức.", "iˈnɔɹməsɫi"],
    ["enterprising", "dám nghĩ dám làm", "ˈɛnɝˌpɹaɪzɪŋ"],
    ["enviable", "- Thật đáng ghen tị.", "ˈɛnviəbəɫ"],
    ["envisage", "dự tính", "ɛnˈvɪzɪdʒ"],
    ["estimation", "ước lượng", "ˌɛstəˈmeɪʃən"],
    ["ethical", "Luân lý học", "ˈɛθɪkəɫ"],
    ["ethically", "• có đạo đức", "ˈɛθɪkəɫi"],
    ["evoke", "gợi lên", "iˈvoʊk"],
    ["liaison", "Liên lạc viên", "ˈɫeɪˌzɑn"],
    ["exert", "nỗ lực", "ɪɡˈzɝt"],
    ["exhibitionist", "người triển lãm", "ˌɛksəˈbɪʃənɪst"],
    ["exhilarate", "phấn khởi", "ɪɡˈzɪɫɝˌeɪt"],
    ["exhilarating", "phấn khởi", "ɪɡˈzɪɫɝˌeɪtɪŋ"],
    ["exhilaration", "phấn khởi", "ɪɡˌzɪɫɝˈeɪʃən"],
    ["likelihood", "Khả năng", "ˈɫaɪkɫiˌhʊd"],
    ["expedite", "tiến hành", "ˈɛkspɪˌdaɪt"],
    ["expire", "kết thúc", "ɪkˈspaɪɹ"],
    ["explanatory", "Giải thích", "ɪksˈpɫænəˌtɔɹi"],
    ["exploitation", "bóc lột", "ˌɛksˌpɫɔɪˈteɪʃən"],
    ["explosively", "bùng nổ", "ˌɛksˈpɫoʊsɪvɫi"],
    ["exterior", "Ngoại thất", "ɪkˈstɪɹiɝ"],
    ["extortion", "sự tống tiền", "ɛkˈstɔɹʃən"],
    ["extravagance", "phung phí", "ɛkˈstɹævəɡəns"],
    ["exuberance", "phấn khởi", "ɪɡˈzubɝəns"],
    ["exuberant", "Cởi mở", "ɪɡˈzubɝənt"],
    ["macabre", "rùng rợn", "məˈkɑbɝ"],
    ["facial", "(thuộc) mặt", "ˈfeɪʃəɫ"],
    ["facilitation", "sự tạo điều kiện thuận lợi", "fəˌsɪɫəˈteɪʃən"],
    ["limitless", "Không bị hạn chế", "ˈɫɪmətɫəs"],
    ["fanatic", "Chính xác hơn, ông ấy không phải mê bóng chày", "fəˈnætɪk"],
    ["fanatically", "cuồng tín", "fəˈnætɪkəɫi"],
    ["fanciful", "Huyền ảo", "ˈfænsɪfəɫ"],
    ["farce", "trò hề", "ˈfɑɹs"],
    ["fatality", "tử vong", "fəˈtæɫɪti"],
    ["fatigue", "mệt mỏi", "fəˈtiɡ"],
    ["ferocious", "dữ tợn", "fɝˈoʊʃəs"],
    ["ferociously", "dữ dội", "fɝˈoʊʃɪsɫi"],
    ["fiddle", "- Bass.", "ˈfɪdəɫ"],
    ["fiddler", "nghệ sĩ viôlông", "ˈfɪdəɫɝ"],
    ["fiend", "quỷ dữ", "ˈfind"],
    ["fiendish", "xảo quyệt", "ˈfindɪʃ"],
    ["fiercely", "dữ dội", "ˈfɪɹsɫi"],
    ["firewall", "Tường lửa", "ˈfaɪɹwɑɫ"],
    ["fissure", "khe nứt", "ˈfɪʃɝ"],
    ["fixture", "tích sản lắp đặt cố định", "ˈfɪkstʃɝ"],
    ["flashback", "- Hồi tưởng!", "ˈfɫæʃˌbæk"],
    ["flask", "lọ", "ˈfɫæsk"],
    ["flatter", "Tôn lên vẻ đẹp", "ˈfɫætɝ"],
    ["flattery", "Hình 1: Minh họa kĩ thuật tâng cầu bằng mu", "ˈfɫætɝi"],
    ["flick", "mỡ cật lợn", "ˈfɫɪk"],
    ["flicker", "Nhầp nháy", "ˈfɫɪkɝ"],
    ["flourish", "xua chân múa tay", "ˈfɫɝɪʃ"],
    ["folktale", "Truyện dân gian", "ˈfoʊkˌteɪɫ"],
    ["forensic", "Pháp y", "ˌfɔˈɹɛnsɪk"],
    ["forfeit", "Để mất, mất quyền, bị tước.", "ˈfɔɹfɪt"],
    ["formality", "thủ tục", "fɔɹˈmæɫəti"],
    ["formulate", "Người lập", "ˈfɔɹmjəˌɫeɪt"],
    ["fossil", "hóa thạch", "ˈfɑsəɫ"],
    ["fraction", "sản phẩm chưng cất", "ˈfɹækʃən"],
    ["fragmentation", "phân rải", "ˌfɹæɡmənˈteɪʃən"],
    ["magnetically", "Từ học", "mæɡˈnɛtɪkəɫi"],
    ["fuse", "hợp nhất", "ˈfjuz"],
    ["fusion", "sự dung hợp", "ˈfjuʒən"],
    ["gadget", "tiện ích", "ˈɡædʒət"],
    ["linear", "tuyến tính", "ˈɫɪniɝ"],
    ["gape", "há hốc miệng", "ˈɡeɪp"],
    ["gem", "Ngọc", "ˈdʒɛm"],
    ["genome", "Hệ genom, bộ gen", "ˈdʒiˌnoʊm"],
    ["geological", "Địa chất học", "ˌdʒiəˈɫɑdʒɪkəɫ"],
    ["ghostly", "ma quái", "ˈɡoʊstɫi"],
    ["gig", "xiên cá", "ˈɡɪɡ"],
    ["glean", "lượm lặt", "ˈɡɫin"],
    ["glum", "ủ rũ", "ˈɡɫəm"],
    ["glumly", "rầu rĩ", "ˈɡɫəmɫi"],
    ["magnetism", "Từ học", "ˈmæɡnəˌtɪzəm"],
    ["linearly", "tuyến tính", "ˈɫɪniɝɫi"],
    ["gourmet", "tay sành ăn", "ˈɡʊɹˌmeɪ"],
    ["graft", "hối lộ", "ˈɡɹæft"],
    ["grapefruit", "quả bưởi chùm", "ˈɡɹeɪpˌfɹut"],
    ["ground", "mặt đất", "ˈɡɹaʊnd"],
    ["grounds", "Luật nào chứ?", "ˈɡɹaʊndz"],
    ["gruesome", "khủng khiếp", "ˈɡɹusəm"],
    ["grumble", "Tổ hợp tên lửa S-300", "ˈɡɹəmbəɫ"],
    ["gush", "sự chảy nhọt ra", "ˈɡəʃ"],
    ["gushing", "phun trào", "ˈɡəʃɪŋ"],
    ["gusto", "Giúp tôi với!", "ˈɡəsˌtoʊ"],
    ["gutsy", "gan dạ", "ˈɡətˈsi"],
    ["gypsy", "đại ca", "ˈdʒɪpsi"],
    ["loom", "khung cửi", "ˈɫum"],
    ["haggle", "sự mặc cả", "ˈhæɡəɫ"],
    ["harass", "quấy rối", "hɝˈæs"],
    ["harvest", "vụ gặt", "ˈhɑɹvəst"],
    ["headstrong", "Cứng đầu", "ˈhɛdˌstɹɔŋ"],
    ["hedgehog", "con nhím", "ˈhɛdʒˌhɑɡ"],
    ["heifer", "bò cái tơ", "ˈhaɪfɝ"],
    ["heighten", "nâng cao", "ˈhaɪtən"],
    ["hence", "sau đây, kế từ đây", "ˈhɛns"],
    ["heroine", "Anh hùng dân tộc", "ˈhɛɹoʊən"],
    ["hibernate", "nghỉ đông, ngủ đông", "ˈhaɪbɝˌneɪt"],
    ["hibernation", "Ngủ đông", "ˌhaɪbɝˈneɪʃən"],
    ["homely", "giản dị", "ˈhoʊmɫi"],
    ["ludicrous", "lố bịch", "ˈɫudəkɹəs"],
    ["hostess", "- Phục vụ?", "ˈhoʊstəs"],
    ["hostile", "thái độ thù địch", "ˈhɑstəɫ"],
    ["hostility", "Chân trời.", "hɑˈstɪɫəti"],
    ["house", "nhà, căn nhà, toàn nhà", "ˈhaʊs"],
    ["hypocrisy", "đạo đức giả", "hɪˈpɑkɹəsi"],
    ["hypocrite", "Đồ đạo đức giả.", "ˈhɪpəˌkɹɪt"],
    ["hypocritical", "đạo đức giả", "ˌhɪpəˈkɹɪtɪkəɫ"],
    ["ludicrously", "lố bịch", "ˈɫudəkɹəsɫi"],
    ["immensely", "Mãn nguyện?", "ˌɪˈmɛnsɫi"],
    ["immortalize", "bất tử hóa", "ˌɪˈmɔɹtəɫaɪz"],
    ["imp", "tiểu yêu", "ˈɪmp"],
    ["impede", "cản trở", "ˌɪmˈpid"],
    ["impediment", "Sự trở ngại", "ˌɪmˈpɛdəmənt"],
    ["impersonal", "và thiếu riêng tư à?", "ˌɪmˈpɝsənəɫ"],
    ["impersonate", "Mạo danh", "ˌɪmˈpɝsəˌneɪt"],
    ["impersonation", "mạo danh", "ˌɪmpɝsəˈneɪʃən"],
    ["impersonator", "kẻ mạo danh", "ˌɪmˈpɝsəneɪtɝ"],
    ["impervious", "không thấm qua được", "ˌɪmˈpɝviəs"],
    ["impish", "thần thánh", "ˈɪmpɪʃ"],
    ["implicate", "liên quan", "ˈɪmpɫɪˌkeɪt"],
    ["impoverished", "Nghèo", "ˌɪmˈpɑvɹɪʃt"],
    ["incision", "Sự căt rạch , Đường rạch", "ˌɪnˈsɪʒən"],
    ["incisor", "RĂNG CƯA", "ˌɪnˈsaɪzɝ"],
    ["inclusion", "bao gồm", "ˌɪnˈkɫuʒən"],
    ["inclusive", "trọn cả hai ngày", "ˌɪnˈkɫusɪv"],
    ["indefinite", "VÔ CỰC", "ˌɪnˈdɛfənət"],
    ["indefinitely", "- Không biết được.", "ˌɪnˈdɛfənətɫi"],
    ["individuality", "Tính cá nhân", "ˌɪnˌdɪvɪdʒuˈæɫɪti"],
    ["induct", "cảm ứng", "ˌɪnˈdəkt"],
    ["induction", "học nghề vỡ lòng", "ˌɪnˈdəkʃən"],
    ["inexcusable", "Không thể tha thứ được.", "ˌɪnɪkˈskjuzəbəɫ"],
    ["inexcusably", "không thể tha thứ được", "ˌɪnɪkˈskjuzəbɫi"],
    ["inexhaustible", "vô tận", "ˌɪnɪɡˈzɔstəbəɫ"],
    ["inexplicable", "Không giải thích được.", "ˌɪnəksˈpɫɪsəbəɫ"],
    ["inexplicably", "không thể giải thích được", "ˌɪnɪksˈpɫɪkəbɫi"],
    ["ingenious", "Rất tài tình", "ˌɪnˈdʒinjəs"],
    ["ingenuity", "khéo léo", "ˌɪndʒəˈnuəˌti"],
    ["inherent", "vốn có", "ɪnˈhɛɹənt"],
    ["inherently", "Vốn có, cố hữu", "ɪnˈhɛɹəntɫi"],
    ["inheritance", "sự thừa kế di sản", "ˌɪnˈhɛɹətəns"],
    ["injustice", "Bất công", "ˌɪnˈdʒəstɪs"],
    ["innovate", "Đổi mới", "ˈɪnəˌveɪt"],
    ["insecure", "Không bảo mật", "ˈɪnsəkjɝ"],
    ["insensitive", "- Nhạy cảm?", "ˌɪnˈsɛnsətɪv"],
    ["insightful", "Sâu sắc", "ˈɪnˌsaɪtfəɫ"],
    ["instinctive", "bản năng", "ˌɪnˈstɪŋktɪv"],
    ["instinctively", "theo bản năng", "ˌɪnˈstɪŋktɪvˌɫi"],
    ["insubordinate", "bất phục tùng", "ˌɪnsəˈbɔɹdəˌneɪt"],
    ["insubordination", "Không làm theo hướng dẫn", "ˌɪnsəˌbɔɹdəˈneɪʃən"],
    ["integral", "tích phân", "ˈɪnəɡɹəɫ"],
    ["intellect", "trí tuệ", "ˈɪnəˌɫɛkt"],
    ["interject", "xen kẽ", "ˌɪntɝˈdʒɛkt"],
    ["interjection", "can thiệp", "ˌɪntɝˈdʒɛkʃən"],
    ["lust", "Ham muốn", "ˈɫəst"],
  ],
  "C2": [
    ["ubiquitous", "có mặt khắp nơi", "juˈbɪkwɪtəs"],
    ["ephemeral", "phù du, ngắn ngủi", "ɪˈfɛmɝəɫ"],
    ["idiosyncratic", "đặc trưng riêng", "ˌɪdioʊˌsɪnˈkɹætɪk"],
    ["pragmatic", "thực dụng", "pɹæɡˈmætɪk"],
    ["disseminate", "phổ biến, truyền bá", "dɪˈsɛməˌneɪt"],
    ["exacerbate", "làm trầm trọng thêm", "ɪɡˈzæsɝˌbeɪt"],
    ["ostensibly", "bề ngoài thì", "ɑˈstɛnsəbɫi"],
    ["equanimity", "sự bình thản", "ˌikwəˈnɪmɪti"],
    ["indefatigable", "không biết mệt mỏi", "ˌɪndɪˈfætɪɡəbəɫ"],
    ["by and large", "nhìn chung", "ˈbaɪ ˈænd ˈɫɑɹdʒ"],
    ["captious", "bị giam cầm"],
    ["magnanimous", "cao thượng", "mæɡˈnænəməs"],
    ["apotheosis", "thần thánh", "əˌpɑθiˈoʊsəs"],
    ["tirade", "đả kích", "taɪˈɹeɪd"],
    ["gregarious", "thích giao du", "ɡɹəˈɡɛɹiəs"],
    ["profligate", "hoang phí", "ˈpɹɔfɫɪˌɡeɪt"],
    ["decry", "chê bai", "dɪˈkɹaɪ"],
    ["castigate", "hành hạ", "ˈkæstəˌɡeɪt"],
    ["antipathy", "phản cảm", "ænˈtɪpəθi"],
    ["mitigate", "giảm thiểu", "ˈmɪtəˌɡeɪt"],
    ["obdurate", "cứng nhắc", "ˈɑbdɝət"],
    ["prosaic", "tục tĩu", "pɹoʊˈzeɪɪk"],
    ["morose", "rầu rĩ", "mɝˈoʊs"],
    ["felicitous", "hạnh phúc", "fɪˈɫɪsətəs"],
    ["pedantic", "mô phạm", "pəˈdæntɪk"],
    ["extant", "còn tồn tại", "ˈɛkstənt"],
    ["obsequious", "khúm núm", "əbˈsikwiəs"],
    ["expatiate", "làm việc ở nước ngoài"],
    ["demagogue", "người mị dân", "ˈdɛməˌɡɑɡ"],
    ["burnish", "đánh bóng", "ˈbɝnɪʃ"],
    ["dubiety", "nghi ngờ"],
    ["languid", "uể oải", "ˈɫæŋɡwəd"],
    ["flout", "hờn dỗi", "ˈfɫaʊt"],
    ["dissemble", "tháo rời", "dɪˈsɛmbəɫ"],
    ["expiate", "đền tội", "ˈɛkspiˌeɪt"],
    ["subvert", "lật đổ", "səbˈvɝt"],
    ["supercilious", "siêu phàm", "ˌsupɝˈsɪɫiəs"],
    ["vacuous", "trống rỗng", "ˈvækjuəs"],
    ["vilify", "phỉ báng", "ˈvɪɫɪˌfaɪ"],
    ["superfluous", "thừa", "ˈsupɝfɫˌwəs"],
    ["desiccate", "sấy", "ˈdɛsəkeɪt"],
    ["abstruse", "khó hiểu", "əbˈstɹus"],
    ["ascetic", "thông tin về nhà sư minh tuệ", "əˈsɛtɪk"],
    ["insouciant", "không nổi bật", "ˌɪnˈsusjənt"],
    ["excoriate", "bệnh da liễu", "ɛkˈskɔɹiˌeɪt"],
    ["relegate", "xuống hạng", "ˈɹɛɫəˌɡeɪt"],
    ["loquacious", "nói tục tĩu", "ɫoʊˈkweɪʃəs"],
    ["euphemism", "khinh từ", "ˈjufəˌmɪzəm"],
    ["dogmatic", "câu nệ giáo điều", "dɑɡˈmætɪk"],
    ["coalesce", "nối lại", "ˌkoʊəˈɫɛs"],
    ["laud", "lời khen ngợi", "ˈɫɔd"],
    ["endemic", "địa phương", "ɛnˈdɛmɪk"],
    ["sanctimonious", "thiêng liêng", "ˌsæŋktəˈmoʊniəs"],
    ["indolent", "vô cảm [tt]", "ˈɪndəɫənt"],
    ["verbose", "dài dòng, dài dòng"],
    ["caustic", "kiềm ăn da", "ˈkɑstɪk"],
    ["onerous", "nặng nề", "ˈoʊnɝəs"],
    ["hubris", "ngạo mạn", "ˈhjubɹəs"],
    ["solipsism", "thuyết duy ngã"],
    ["soporific", "thuốc ngủ"],
    ["desultory", "bỏ hoang", "ˈdɛsəɫˌtɔɹi"],
    ["bellicose", "bướng bỉnh", "ˈbɛɫəˌkoʊs"],
    ["antithesis", "phản đề", "ænˈtɪθəsəs"],
    ["remonstrate", "phản đối"],
    ["obviate", "tránh", "ˈɑbviˌeɪt"],
    ["expunge", "xóa bỏ", "ɪkˈspəndʒ"],
    ["nascent", "mới ra đời", "ˈneɪsənt"],
    ["abhor", "ghê tởm", "æbˈhɔɹ"],
    ["abhorrent", "gớm ghiếc", "æbˈhɔɹənt"],
    ["nigh", "gần", "ˈnaɪ"],
    ["abundantly", "dồi dào", "əˈbəndəntɫi"],
    ["accountability", "trách nhiệm giải trình", "əˈkaʊnəbɪɫɪti"],
    ["accrue", "tính dồn lại", "əˈkɹu"],
    ["acreage", "diện tích (tính theo mẫu Anh)", "ˈeɪkɝɪdʒ"],
    ["acrobatic", "nhào lộn", "ˌækɹəˈbætɪk"],
    ["acrobatics", "nhào lộn", "ˌækɹəˈbætɪks"],
    ["additive", "chất phụ gia", "ˈædətɪv"],
    ["adept", "lão luyện", "əˈdɛpt"],
    ["adhere", "dính chặt", "ədˈhɪɹ"],
    ["adhesion", "sự dính chặt", "ædˈhiʒən"],
    ["adornment", "Đẹp", "əˈdɔɹnmənt"],
    ["adulterate", "pha thêm vào", "əˈdəɫtɝˌeɪt"],
    ["affectation", "ảnh hưởng", "ˌæfɛkˈteɪʃən"],
    ["agency", "tác dụng, lực", "ˈeɪdʒənsi"],
    ["aghast", "kinh ngạc", "əˈɡæst"],
    ["agile", "linh hoạt", "ˈædʒəɫ"],
    ["agility", "Nhanh nhẹn", "əˈdʒɪɫəti"],
    ["allegorical", "Phúng dụ", "ˌæɫəˈɡɔɹəkəɫ"],
    ["allegory", "Nói bóng", "ˈæɫəˌɡɔɹi"],
    ["allot", "phân phát (cổ phiếu)", "əˈɫɑt"],
    ["allotment", "việc phân phối cổ phiếu", "əˈɫɑtmənt"],
    ["allude", "ám chỉ", "əˈɫud"],
    ["allusion", "ám chỉ", "əˈɫuʒən"],
    ["amorphous", "vô định hình", "əˈmɔɹfəs"],
    ["anarchic", "vô chính phủ", "æˈnɑɹkɪk"],
    ["angst", "sợ hãi", "ˈɑŋkst"],
    ["angular", "có góc cạnh", "ˈæŋɡjəɫɝ"],
    ["annex", "phụ kiện", "ˈæˌnɛks"],
    ["anonymity", "Tính ẩn danh", "ˌænəˈnɪmɪti"],
    ["anthology", "Tuyển tập", "ænˈθɑɫədʒi"],
    ["anthropological", "Nhân chủng học", "ˌænθɹəpəˈɫɑdʒəkəɫ"],
    ["antidote", "thuốc giải độc", "ˈænɪˌdoʊt"],
    ["antithetical", "đối lập", "ˌæntəˈθɛtɪkəɫ"],
    ["apostle", "sứ đồ", "əˈpɑsəɫ"],
    ["apprehend", "Tiếp thu", "ˌæpɹɪˈhɛnd"],
    ["aptitude", "năng lực", "ˈæptəˌtud"],
    ["arcane", "phức tạp", "ˌɑɹˈkeɪn"],
    ["nonchalant", "Chúng tôi thành thật xin lỗi", "ˌnɑnʃəˈɫɑnt"],
    ["archetype", "nguyên mẫu", "ˈɑɹkɪˌtaɪp"],
    ["archival", "lưu trữ", "ɑɹˈkaɪvəɫ"],
    ["nonchalantly", "thờ ơ", "ˈnɑnʃəˈɫɑntɫi"],
    ["articulation", "Phát âm", "ˌɑɹtɪkjəˈɫeɪʃən"],
    ["artifact", "đồ tạo tác", "ˈɑɹtəˌfækt"],
    ["artifice", "tạo tác", "ˈɑɹtəfɪs"],
    ["assimilate", "Đồng hóa", "əˈsɪməˌɫeɪt"],
    ["assimilation", "sự tiêu hóa", "əˌsɪməˈɫeɪʃən"],
    ["astringent", "chất làm chát", "əˈstɹɪndʒənt"],
    ["athleticism", "- Kĩ thuật.", "æθˈɫɛtɪˌsɪzm"],
    ["attrition", "Sự hao mòn", "əˈtɹɪʃən"],
    ["attuned", "hài hòa", "əˈtund"],
    ["austere", "chát", "ɔˈstɪɹ"],
    ["austerely", "khắc khổ", "ˌɔˈstɪɹɫi"],
    ["austerity", "khổ hạnh", "ˌɔˈstɛɹɪti"],
    ["authenticity", "tính xác thực", "ˌɔθənˈtɪsɪti"],
    ["automate", "tự động hóa", "ˈɔtəˌmeɪt"],
    ["autonomous", "tự trị, tự quản, tự điều khiển", "ɔˈtɑnəməs"],
    ["autonomously", "tự chủ", "ˌɔˈtɑnoʊməsɫi"],
    ["autopilot", "chế độ tự lái", "ˈɔtoʊˌpaɪɫət"],
    ["averse", "không thích", "əˈvɝs"],
    ["avian", "gia cầm", "ˈeɪviən"],
    ["axiom", "tiền đề", "ˈæksiəm"],
    ["axiomatic", "tiên đề", "ˌæksiəˈmætɪk"],
    ["babble", "lảm nhảm", "ˈbæbəɫ"],
    ["banish", "Lưu đày", "ˈbænɪʃ"],
    ["banishment", "Lưu đày", "ˈbænɪʃmənt"],
    ["nostalgia", "thương", "nɔˈstæɫdʒə"],
    ["bauble", "đồ trang sức", "ˈbɔbəɫ"],
    ["behest", "chỉ thị", "bɪˈhɛst"],
    ["belligerence", "hiếu chiến", "bəˈɫɪdʒɝəns"],
    ["belligerent", "tham chiến", "bəˈɫɪdʒɝənt"],
    ["beneficiary", "nước thụ hưởng", "ˌbɛnəˈfɪʃiˌɛɹi"],
    ["bereft", "mất người thân", "bɝˈɛft"],
    ["besiege", "Bao vây", "bɪˈsidʒ"],
    ["blandishment", "nhạt nhẽo", "ˈbɫændɪʃmənt"],
    ["blight", "(bệnh) lụi", "ˈbɫaɪt"],
    ["blitz", "chớp nhoáng", "ˈbɫɪts"],
    ["blubber", "mỡ cá voi", "ˈbɫəbɝ"],
    ["blurb", "lời giới thiệu ngắn", "ˈbɫɝb"],
    ["bogus", "không thật", "ˈboʊɡəs"],
    ["bout", "Về...", "ˈbaʊt"],
    ["notoriety", "tai tiếng", "ˌnoʊtɝˈaɪəti"],
    ["breadwinner", "người trụ cột trong một gia đình", "ˈbɹɛdˌwɪnɝ"],
    ["brevity", "tính ngắn gọn", "ˈbɹɛvəti"],
    ["brim", "vành", "ˈbɹɪm"],
    ["brimstone", "lưu huỳnh", "ˈbɹɪmstoʊn"],
    ["brink", "bờ vực", "ˈbɹɪŋk"],
    ["brood", "ổ", "ˈbɹud"],
    ["notoriously", "khét tiếng", "noʊˈtɔɹiəsɫi"],
    ["oblique", "xiên", "əˈbɫik"],
    ["burgeoning", "Bò tót", "ˈbɝdʒənɪŋ"],
    ["buzzard", "chim ó", "ˈbəzɝd"],
    ["octogenarian", "Lão hóa", "ˌɑktədʒɪˈnɛɹiən"],
    ["calamitous", "tai họa", "kəˈɫæmətəs"],
    ["calamity", "tai ương", "kəˈɫæməti"],
    ["callous", "(có) chai", "ˈkæɫəs"],
    ["callously", "nhẫn tâm", "ˈkæɫəsɫi"],
    ["capacious", "Khả năng chứa", "kəˈpeɪʃəs"],
    ["opacity", "Độ Đục", "oʊˈpæsəti"],
    ["choreography", "Vũ đạo", "ˌkɔɹiˈɑɡɹəfi"],
    ["chronologically", "theo niên đại", "ˌkɹɑnəˈɫɑdʒɪkɫi"],
    ["chronology", "sự sắp xếp theo niên đại", "kɹəˈnɑɫədʒi"],
    ["opaque", "mờ", "oʊˈpeɪk"],
    ["cinematographer", "Thợ quay phim", "ˌsɪnɪməˈtɑɡɹəfɝ"],
    ["cinematography", "Kỹ thuật điện ảnh", "ˌsɪnɪməˈtɑɡɹəfi"],
    ["circumnavigate", "đi vòng quanh", "ˌsɝkəmˈnævəˌɡeɪt"],
    ["plutocrat", "nhà tài phiệt", "ˈpɫutəˌkɹæt"],
    ["cloister", "tu viện", "ˈkɫɔɪstɝ"],
    ["cloistered", "ẩn dật", "ˈkɫɔɪstɝd"],
    ["coax", "Cáp đồng trục", "ˈkoʊks"],
    ["cocoon", "kén", "kəˈkun"],
    ["opulence", "sự phong phú", "ˈɑpjəɫəns"],
    ["cognitive", "nhận thức", "ˈkɑɡnɪtɪv"],
    ["collide", "va chạm", "kəˈɫaɪd"],
    ["opulent", "Giàu", "ˈɑpjəɫənt"],
    ["colloquial", "thông tục", "kəˈɫoʊkwiəɫ"],
    ["colloquium", "hội thảo chuyên đề", "kəˈɫoʊkwiəm"],
    ["combustion", "đốt cháy", "kəmˈbəstʃən"],
    ["commensurate", "tương xứng", "kəˈmɛnsɝət"],
    ["commensurately", "tương xứng", "kəˈmɛnsɝətɫi"],
    ["ordain", "ra lệnh", "ɔɹˈdeɪn"],
    ["commodity", "thế phẩm", "kəˈmɑdəti"],
    ["compellingly", "hấp dẫn", "kəmˈpɛɫɪŋɫi"],
    ["conciliation", "sự điều giải", "kənˌsɪɫiˈeɪʃən"],
    ["conciliatory", "hòa giải", "kənˈsɪˌɫiəˌtɔɹi"],
    ["concurrence", "sự đồng thuận", "kənˈkɝəns"],
    ["condensation", "sự ngưng tụ", "ˌkɑndənˈseɪʃən"],
    ["ornate", "trang trí công phu", "ɔɹˈneɪt"],
    ["conduit", "ống dẫn", "ˈkɑnduɪt"],
    ["confabulation", "Chứng bịa chuyện", "kənˌfæbjəˈɫeɪʃən"],
    ["confection", "sự làm bánh kẹo", "kənˈfɛkʃən"],
    ["confrontational", "đối đầu", "ˌkɑnfɹənˈteɪʃənəɫ"],
    ["conglomerate", "đòng", "kənˈɡɫɑmɝət"],
    ["conjecture", "- Phỏng đoán?", "kənˈdʒɛkʃɝ"],
    ["connotation", "ý nghĩa)", "ˌkɑnəˈteɪʃən"],
    ["ostensible", "bề ngoài", "ɑˈstɛnsəbəɫ"],
    ["consign", "ủy thác", "kənˈsaɪn"],
    ["consignment", "việc gửi hàng", "kənˈsaɪnmənt"],
    ["consternation", "kinh ngạc", "ˌkɑnstɝˈneɪʃən"],
    ["constrained", "bị hạn chế", "kənˈstɹeɪnd"],
    ["contagion", "(sự) lây, truyền nhiễm", "kənˈteɪdʒən"],
    ["contemptuous", "khinh thường", "kənˈtɛmptʃuəs"],
    ["contemptuously", "khinh bỉ", "kənˈtɛmptʃwəsɫi"],
    ["contractual", "theo hợp đồng", "kənˈtɹæktʃuəɫ"],
    ["contractually", "theo hợp đồng", "kənˈtɹæktʃuəɫi"],
    ["outmoded", "lỗi thời", "ˌaʊtˈmoʊdɪd"],
    ["contrive", "tính toán", "kənˈtɹaɪv"],
    ["cordon", "gờ dạng dây", "ˈkɔɹdən"],
    ["corpse", "xác chết", "ˈkɔɹps"],
    ["corpus", "vốn gốc", "ˈkɔɹpəs"],
    ["correlate", "liên hệ", "ˈkɔɹəˌɫeɪt"],
    ["cosmic", "vũ trụ", "ˈkɑzmɪk"],
    ["cosset", "Nâng niu", "ˈkɑsət"],
    ["counsel", "luật sư, cố vấn luật pháp", "ˈkaʊnsəɫ"],
    ["counterproductive", "Phản tác dụng", "ˈkaʊntɝpɹəˌdəktɪv"],
    ["crippling", "làm tê liệt", "ˈkɹɪpəɫɪŋ"],
    ["painstaking", "siêng năng", "ˈpeɪnˌsteɪkɪŋ"],
    ["cull", "sự phân loại", "ˈkəɫ"],
    ["painstakingly", "cẩn thận", "ˈpeɪnˌsteɪkɪŋɫi"],
    ["curator", "người phụ trách", "ˈkjʊɹətɝ"],
    ["dampen", "làm ẩm", "ˈdæmpən"],
    ["deaden", "làm chết dần", "ˈdɛdən"],
    ["deficient", "Kém", "dɪˈfɪʃənt"],
    ["delicatessen", "thức ăn ngon nấu sẵn", "ˌdɛɫɪkəˈtɛsən"],
    ["demystify", "làm sáng tỏ", "diˈmɪstəˌfaɪ"],
    ["denote", "tỏ rõ, biểu thị", "dɪˈnoʊt"],
    ["denounce", "tuyên bố bãi ước", "dɪˈnaʊns"],
    ["denunciation", "tuyên bố bãi ước", "dɪˌnənsiˈeɪʃən"],
    ["depraved", "đồi trụy", "diˈpɹeɪvd"],
    ["depravity", "suy đồi", "dɪˈpɹævəti"],
    ["deprecate", "Ko tán thành", "ˈdɛpɹəˌkeɪt"],
    ["depressive", "Trầm cảm", "dɪˈpɹɛsɪv"],
    ["derelict", "vô chủ", "ˈdɛɹəˌɫɪkt"],
    ["derision", "chế giễu", "dɝˈɪʒən"],
    ["derisive", "chế nhạo", "dɝˈaɪsɪv"],
    ["derisively", "chế giễu", "dɝˈaɪsɪvɫi"],
    ["deterrent", "răn đe", "dɪˈtɝɹənt"],
    ["detract", "Phân tâm", "dɪˈtɹækt"],
    ["deviant", "lệch lạc", "ˈdiviənt"],
    ["diffuse", "khuếch tán", "dɪfˈjus"],
    ["diligently", "siêng năng", "ˈdɪɫədʒəntɫi"],
    ["diminish", "giảm dần", "dɪˈmɪnɪʃ"],
    ["disdainful", "khinh bỉ", "dɪsˈdeɪnfəɫ"],
    ["disparage", "miệt thị", "dɪˈspɛɹɪdʒ"],
    ["disparaging", "miệt thị", "dɪˈspɛɹɪdʒɪŋ"],
    ["disparagingly", "miệt thị", "dɪˈspɛɹɪdʒɪŋɫi"],
    ["dispersal", "phân tán,", "dɪˈspɝsəɫ"],
    ["disperse", "phân tán", "dɪˈspɝs"],
    ["dissemination", "(sự) phân toả", "dɪˌsɛməˈneɪʃən"],
    ["dissension", "bất đồng quan điểm", "dɪˈsɛnʃən"],
    ["distill", "Chưng cất", "dɪˈstɪɫ"],
    ["distillation", "chiết xuất", "ˌdɪstəˈɫeɪʃən"],
    ["divination", "Bói toán", "ˌdɪvəˈneɪʃən"],
    ["domesticity", "nội địa hóa", "ˌdoʊˌmɛsˈtɪsəti"],
    ["palate", "vị", "ˈpæɫət"],
    ["drudgery", "Công nhân", "ˈdɹədʒɝi"],
    ["dubiously", "đáng ngờ", "ˈdubiəˌsɫi"],
    ["dwarfism", "hiện tượng lùn", "ˈdwɔɹfɪzəm"],
    ["parable", "câu chuyện ngụ ngôn", "ˈpɛɹəbəɫ"],
    ["eccentricity", "độ lệch tâm", "ˌɛksənˈtɹɪsəti"],
    ["echo", "tiếng vọng, sóng dội .", "ˈɛkoʊ"],
    ["echolocation", "Định vị qua tiếng vang.", "ˌɛkoʊɫoʊˈkeɪʃən"],
    ["edification", "Thuộc về pháp lịnh", "ˌɛdəfəˈkeɪʃən"],
    ["edifice", "Tòa nhà", "ˈɛdəfəs"],
    ["edify", "gây dựng", "ˈɛdəˌfaɪ"],
    ["egalitarian", "Chủ nghĩa quân bình", "ɪˌɡæɫəˈtɛɹiən"],
    ["elasticity", "độ co giãn", "ˌiˌɫæsˈtɪsəti"],
    ["elated", "phấn khởi", "ɪˈɫeɪtəd"],
    ["elation", "Phấn khởi", "ɪˈɫeɪʃən"],
    ["electrode", "điện cực", "ˌɪˈɫɛktɹoʊd"],
    ["paradoxical", "nghịch lý", "ˌpɛɹəˈdɑksɪkəɫ"],
    ["embed", "nhúng", "ɪmˈbɛd"],
    ["embodiment", "PHƯƠNG ÁN", "ɛmˈbɑdimənt"],
    ["embody", "hóa thân", "ɪmˈbɑdi"],
    ["eminence", "Đức giáo chủ.", "ˈɛmənəns"],
    ["eminent", "xuất sắc", "ˈɛmənənt"],
    ["emulate", "thi đua", "ˈɛmjəˌɫeɪt"],
    ["emulation", "Thi đua", "ˌɛmjəˈɫeɪʃən"],
    ["emulsifier", "thiết bị tạo nhũ tương", "ɪˈməɫsəˌfaɪɝ"],
    ["enabler", "người hỗ trợ", "ɛˈneɪbəɫɝ"],
    ["encompass", "bao gồm", "ɛnˈkəmpəs"],
    ["encumber", "người gây trở ngại", "ɛnˈkəmbɝ"],
    ["engender", "người tạo ra", "ɛnˈdʒɛndɝ"],
    ["enthuse", "niềm say mê", "ɪnˈθuz"],
    ["epoxy", "Nhựa epoxy", "ɪˈpɑksi"],
    ["equable", "công bằng", "ˈɛkwəbəɫ"],
    ["equilibrium", "thăng bằng", "ˌikwəˈɫɪbɹiəm"],
    ["etch", "Khắc axit", "ˈɛtʃ"],
    ["etching", "sự ăn mòn", "ˈɛtʃɪŋ"],
    ["paradoxically", "nghịch lý", "ˌpɛɹəˈdɑksəkəɫi"],
    ["euphemistic", "uyển ngữ", "ˌjufəˈmɪstɪk"],
    ["euphemistically", "uyển chuyển", "ˌjufəˈmɪstɪkɫi"],
    ["euphoria", "CỰC LẠC Dịch phụ đề: QKK", "juˈfɔɹiə"],
    ["euphoric", "hưng phấn", "juˈfɔɹɪk"],
    ["exalted", "đề cao", "ɪɡˈzɔɫtɪd"],
    ["exorcism", "trừ tà", "ˈɛksɝˌsɪzəm"],
    ["exorcist", "nhà trừ tà", "ˈɛksɝsəst"],
    ["extracurricular", "Hoạt động", "ˌɛkstɹəkɝˈɪkjəɫɝ"],
    ["exude", "sự tiết ra", "ɪɡˈzud"],
    ["fabled", "truyền thuyết", "ˈfeɪbəɫd"],
    ["fabricate", "nguỵ tạo", "ˈfæbɹəˌkeɪt"],
    ["fabrication", "việc chế tạo", "ˌfæbɹɪˈkeɪʃən"],
    ["facsimile", "sự sao lại", "fækˈsɪməɫi"],
    ["fallacy", "ngụy biện", "ˈfæɫəsi"],
    ["farcical", "khôi hài", "ˈfɑɹsəkəɫ"],
    ["feign", "Cử", "ˈfeɪn"],
    ["ferocity", "tàn bạo", "fɝˈɑsəti"],
    ["parasitic", "ký sinh trùng", "ˌpɛɹəˈsɪtɪk"],
    ["figuratively", "nghĩa bóng", "fɪɡˈjʊɹətɪvɫi"],
    ["flagging", "cờ hiệu", "ˈfɫæɡɪŋ"],
    ["parochial", "địa phương", "pɝˈoʊkiəɫ"],
    ["patchy", "loang lổ", "ˈpætʃi"],
    ["pedestal", "khung bơm ly tâm", "ˈpɛdəstəɫ"],
    ["floodgates", "cửa xả lũ", "ˈfɫədˌɡeɪts"],
    ["fluctuate", "thay đổi bất thường", "ˈfɫəktʃəˌweɪt"],
    ["fluctuation", "sự thịnh suy (kinh tế, thương mại)", "ˌfɫəktʃuˈeɪʃən"],
    ["forfeiture", "tước quyền", "ˈfɔɹfətʃɝ"],
    ["forlorn", "tuyệt vọng", "fɝˈɫɔɹn"],
    ["formidably", "ghê gớm", "ˈfɔɹmədəbɫi"],
    ["fractious", "gãy xương", "ˈfɹækʃəs"],
    ["frolic", "vui nhộn", "ˈfɹɑɫɪk"],
    ["fruition", "đơm hoa kết trái", "fɹuˈɪʃən"],
    ["polysyllabic", "Âm tiết", "ˌpɑˌɫisɪˈɫæbɪk"],
    ["perch", "địa vị cao quý", "ˈpɝtʃ"],
    ["pervasive", "tràn lan khắp", "pɝˈveɪsɪv"],
    ["pervasiveness", "Phát triển mạnh", "pɝˈveɪsɪvnɪs"],
    ["glitzy", "hào nhoáng", "ˈɡɫɪtsi"],
    ["gout", "bệnh gút", "ˈɡaʊt"],
    ["gravitate", "Lực hấp dẫn", "ˈɡɹævɪˌteɪt"],
    ["gravitational", "Tương tác hấp dẫn", "ˌɡɹævɪˈteɪʃənəɫ"],
    ["gravitationally", "hấp dẫn", "ˌɡɹævəˈteɪʃnəɫi"],
    ["grievance", "Khiếu nại", "ˈɡɹivəns"],
    ["habitation", "sự cư trú", "ˌhæbəˈteɪʃən"],
    ["hamper", "giỏ có nắp đựng thực phẩm", "ˈhæmpɝ"],
    ["haphazard", "lộn xộn", "hæpˈhæzɝd"],
    ["haphazardly", "một cách bừa bãi", "ˈhæfəzɝdɫi"],
    ["hapless", "Cá mập", "ˈhæpɫəs"],
    ["happenstance", "ngẫu nhiên", "ˈhæpənˌstæns"],
    ["haughtily", "kiêu ngạo", "ˈhɔtɪɫi"],
    ["haughty", "[Kiêu căng]", "ˈhɔti"],
    ["hauntingly", "ám ảnh", "ˈhɔntɪŋɫi"],
    ["headmistress", "- Bà Hiệu trưởng nào?", "ˈhɛdˌmɪstɹəs"],
    ["helm", "bánh lái", "ˈhɛɫm"],
    ["herald", "- Sứ giả.", "ˈhɛɹəɫd"],
    ["hermit", "bánh qui có nho và hạt dẻ", "ˈhɝmət"],
    ["hinder", "cản trở", "ˈhɪndɝ"],
    ["hindrance", "trở ngại", "ˈhɪndɹəns"],
    ["hindsight", "nhận thức muộn", "ˈhaɪnˌsaɪt"],
    ["histrionic", "lịch sử", "ˌhɪstɹiˈɑnɪk"],
    ["hitch", "Xô", "ˈhɪtʃ"],
    ["hitherto", "cho đến nay", "ˈhɪˌðɝˈtu"],
    ["hoist", "trục tải", "ˈhɔɪst"],
    ["perverse", "Hư hỏng", "pɝˈvɝs"],
    ["hotelier", "chủ khách sạn", "hoʊˈtɛɫjɝ"],
    ["huddle", "trò chuyện thân mật", "ˈhədəɫ"],
    ["hull", "thân tàu", "ˈhəɫ"],
    ["hypothesis", "giả thuyết", "haɪˈpɑθəsəs"],
    ["hypothesize", "Giả định", "haɪˈpɑθəˌsaɪz"],
    ["hypothetical", "Giả thuyết", "ˌhaɪpəˈθɛtəkəɫ"],
    ["perversity", "sự đồi trụy", "pɝˈvɝsəti"],
    ["philanthropic", "hoạt động từ thiện", "ˌfɪɫənˈθɹɑpɪk"],
    ["hysterically", "cuồng loạn", "ˌhɪsˈtɛɹɪkɫi"],
    ["idiomatic", "thành ngữ", "ˌɪdiəˈmætɪk"],
    ["idiosyncrasy", "Đặc-ứng", "ˌɪdioʊˈsɪnkɹəˌsi"],
    ["ignominious", "đáng xấu hổ", "ˌɪɡnəˈmɪniəs"],
    ["impeccable", "hoàn hảo", "ˌɪmˈpɛkəbəɫ"],
    ["impeccably", "hoàn hảo", "ˌɪmˈpɛkəbɫi"],
    ["imperceptible", "Tri giác", "ˌɪmpɝˈsɛptɪbəɫ"],
    ["imperceptibly", "không thể nhận thấy", "ˌɪmpɝˈsɛptɪbɫi"],
    ["imposition", "thuế", "ˌɪmpəˈzɪʃən"],
    ["impresario", "Bầu sô", "ˌɪmpɹɪˈsɑɹiˌoʊ"],
    ["impressionistic", "Trường phái ấn tượng", "ˌɪmˌpɹɛʃəˈnɪstɪk"],
    ["improvisational", "ứng biến", "ˌɪmpɹɑvɪˈzeɪʃənəɫ"],
    ["inchoate", "nhạt nhẽo", "ˌɪnˈkoʊət"],
    ["incipient", "phôi thai", "ˌɪnˈsɪpiənt"],
    ["incise", "vết thương", "ˌɪnˈsaɪz"],
    ["incongruity", "không phù hợp", "ˌɪŋkɔŋˈɹuɪti"],
    ["incongruous", "không phù hợp", "ˌɪŋˈkɔŋɹuəs"],
    ["incongruously", "không phù hợp", "ˌɪŋˈkɔŋɹuəsɫi"],
    ["incumbent", "đương chức", "ˌɪnˈkəmbənt"],
    ["indignant", "phẫn nộ", "ˌɪnˈdɪɡnənt"],
    ["indignantly", "phẫn nộ", "ˌɪnˈdɪɡnəntˌɫi"],
    ["indiscretion", "không thận trọng", "ˌɪndɪsˈkɹɛʃən"],
    ["individualism", "chủ nghĩa bất can thiệp", "ˌɪndɪvɪˈduəˌɫɪzəm"],
    ["induce", "thúc sinh", "ˌɪnˈdus"],
    ["inducement", "vật dẫn dụ", "ˌɪnˈdusmənt"],
    ["indulgence", "sự triển hạn trả tiền", "ˌɪnˈdəɫdʒəns"],
    ["inexorable", "không thể lay chuyển", "ˌɪˈnɛksɝəbəɫ"],
    ["inexorably", "không nao núng", "ˌɪˈnɛksɝəbɫi"],
    ["infallibility", "không thể sai lầm", "ˌɪnˌfæɫɪˈbɪɫɪti"],
    ["infallible", "không thể sai lầm", "ˌɪnˈfæɫəbəɫ"],
    ["infernal", "địa ngục", "ˌɪnˈfɝnəɫ"],
    ["informant", "người đi khai sinh", "ˌɪnˈfɔɹmənt"],
    ["ingenuous", "ngây thơ", "ˌɪnˈdʒɛnjuəs"],
    ["ingratiate", "xâm nhập", "ˌɪŋˈɡɹeɪʃiˌeɪt"],
    ["ingratiating", "nhập khẩu", "ˌɪŋˈɡɹeɪʃiˌeɪtɪŋ"],
    ["innuendo", "ám chỉ", "ˌɪnjuˈɛndoʊ"],
    ["inscrutable", "không thể hiểu được", "ˌɪnsˈkɹutəbəɫ"],
    ["instantaneous", "từ tức thời", "ˌɪnstənˈtæniəs"],
    ["instantaneously", "ngay lập tức", "ˌɪnstənˈtæniəsɫi"],
    ["insular", "thể cách biệt", "ˈɪnsəɫɝ"],
    ["integration", "hội nhập", "ˌɪnəˈɡɹeɪʃən"],
    ["philanthropist", "nhà từ thiện", "fəˈɫænθɹəpəst"],
    ["interlude", "thời gian nghỉ giải lao", "ˈɪntɝˌɫud"],
    ["intermediary", "người tổ chức trung gian", "ˌɪnɝˈmidiɛɹi"],
    ["interrogate", "thẩm vấn", "ˌɪnˈtɛɹəˌɡeɪt"],
    ["interrogation", "câu truy vấn", "ˌɪnˌtɛɹəˈɡeɪʃən"],
    ["intersperse", "xen kẽ", "ˌɪntɝˈspɝs"],
    ["interweave", "đan xen", "ˌɪntɝˈwiv"],
    ["philanthropy", "Tổ chức phúc thiện", "fɪˈɫænθɹəpi"],
    ["intrinsically", "bản chất.", "ˌɪnˈtɹɪnsɪkəɫi"],
    ["irrelevancy", "không liên quan", "ˌɪˈɹɛɫəvənsi"],
    ["irrevocable", "Liên quan, dích líu.", "ˌɪˈɹɛvəkəbəɫ"],
    ["irrevocably", "không thể hủy ngang", "ˌɪˈɹɛvəkəbɫi"],
    ["jargon", "tiếng lóng", "ˈdʒɑɹɡən"],
    ["jarring", "chói tai", "ˈdʒɑɹɪŋ"],
    ["kinetic", "động học", "kəˈnɛtɪk"],
    ["knack", "sở trường", "ˈnæk"],
    ["lament", "Rên rỉ", "ɫəˈmɛnt"],
    ["laryngitis", "Viêm thanh quản", "ˌɫɑɹɪnˈdʒaɪtəs"],
    ["laudatory", "khen ngợi", "ˈɫɔdəˌtɔɹi"],
    ["physiological", "(thuộc) sinh lý, sinh lý học", "ˌfɪziəˈɫɑdʒɪkəɫ"],
    ["leavening", "chất làm nở", "ˈɫɛvənɪŋ"],
    ["legion", "Quân đoàn", "ˈɫidʒən"],
    ["physiologically", "sinh lý học", "ˌfɪziəˈɫɑdʒɪkɫi"],
    ["locomotive", "Đầu máy", "ˌɫoʊkəˈmoʊtɪv"],
    ["loiter", "người đi lang thang", "ˈɫɔɪtɝ"],
    ["lurid", "Quá ngớ ngẩn.", "ˈɫʊɹəd"],
    ["lyrical", "trữ tình", "ˈɫɪɹɪkəɫ"],
    ["lyrically", "lời bài hát", "ˈɫɪɹɪkɫi"],
    ["lyricist", "Người viết lời bài hát", "ˈɫɪɹɪsɪst"],
    ["maelstrom", "Nước xoáy.", "ˈmeɪɫstɹəm"],
    ["maggot", "giòi (mồi) sâu", "ˈmæɡət"],
    ["magnate", "vua công nghiệp", "ˈmæɡˌneɪt"],
    ["magpie", "Ác là", "ˈmæɡˌpaɪ"],
    ["malice", "ác ý", "ˈmæɫəs"],
    ["malicious", "độc hại", "məˈɫɪʃəs"],
    ["maliciously", "ác ý", "məˈɫɪʃɪsɫi"],
    ["malleability", "Độ dẻo", "ˌmæɫiəˈbɪɫəti"],
    ["malleable", "Độ dẻo", "ˈmæɫiəbəɫ"],
    ["mangle", "mảnh vụn", "ˈmæŋɡəɫ"],
    ["mariner", "thủy thủ", "ˈmɛɹənɝ"],
    ["marketability", "khả năng tiếp thị", "ˌmɑɹkɪtəˈbɪɫɪti"],
    ["materialism", "chủ nghĩa duy vật", "məˈtɪɹiəˌɫɪzəm"],
    ["materialistic", "duy vật", "məˌtɪɹiəˈɫɪstɪk"],
    ["maverick", "Maverick! Maverick!", "ˈmævɝɪk"],
    ["mediate", "hòa giải", "ˈmidiˌeɪt"],
    ["mediation", "sự trung gian dàn xếp", "ˌmidiˈeɪʃən"],
    ["mediocrity", "tầm thường", "ˌmidiˈɑkɹəti"],
    ["melancholy", "u sầu", "ˈmɛɫənˌkɑɫi"],
    ["melodious", "du dương", "məˈɫoʊdiəs"],
    ["menace", "sự đe dọa", "ˈmɛnəs"],
    ["menacing", "đe dọa", "ˈmɛnəsɪŋ"],
    ["menacingly", "(đe dọa)", "ˈmɛnəsɪŋɫi"],
    ["menial", "Người giúp việc", "ˈminiəɫ"],
    ["mercantile", "thuộc về buôn", "ˈmɝkənˌtaɪɫ"],
    ["mercenary", "Lính đánh thuê", "ˈmɝsəˌnɛɹi"],
    ["merit", "giá trị", "ˈmɛɹət"],
    ["mesh", "mắc lưới", "ˈmɛʃ"],
    ["meteorological", "khí tượng học", "ˌmitiˌɔɹəˈɫɑdʒɪkəɫ"],
    ["meteorology", "Khí tượng học", "ˌmitiɝˈɑɫədʒi"],
    ["methodological", "phương pháp luận", "ˌmɛθədəˈɫɑdʒɪkəɫ"],
    ["methodology", "phương học", "ˌmɛθəˈdɑɫədʒi"],
    ["meticulously", "tỉ mỉ", "məˈtɪkjəɫəsɫi"],
    ["midwifery", "Hộ sinh", "ˈmɪdˌwaɪfɝi"],
    ["plane", "mặt phẳng, mặt bằng", "ˈpɫeɪn"],
    ["milieu", "Môi trường", "mɪɫˈjʊ"],
    ["minefield", "vùng mỏ", "ˈmaɪnˌfiɫd"],
    ["plumage", "bộ lông", "ˈpɫumədʒ"],
    ["modernism", "tư trào", "ˈmɑdɝˌnɪzəm"],
    ["monastic", "tu viện", "məˈnæstɪk"],
    ["moor", "Đồng hoang/cột, buộc", "ˈmʊɹ"],
    ["moribund", "hấp hối", "ˈmɔɹəbənd"],
    ["mottled", "lốm đốm", "ˈmɑtəɫd"],
    ["mutinous", "nổi loạn", "ˈmjutənəs"],
    ["myriad", "gấp vạn lần đơn vị cơ bản", "ˈmɪɹiəd"],
    ["ponderous", "Ponderous - béo phì", "ˈpɑndɝəs"],
  ],
};
