const WORDS_DB = {
  "B1": [
    ["hospital", "bệnh viện"],
    ["weather", "thời tiết"],
    ["holiday", "kỳ nghỉ"],
    ["kitchen", "nhà bếp"],
    ["morning", "buổi sáng"],
    ["market", "chợ"],
    ["teacher", "giáo viên"],
    ["family", "gia đình"],
    ["hungry", "đói bụng"],
    ["travel", "du lịch"],
    ["forget", "quên"],
    ["borrow", "mượn"],
    ["arrive", "đến nơi"],
    ["decide", "quyết định"],
    ["neighbor", "hàng xóm"],
    ["yesterday", "hôm qua"],
    ["haven", "nơi trú ẩn"],
    ["accompany", "kèm theo"],
    ["liberate", "giải phóng"],
    ["ache", "đau nhức;nhức nhối"],
    ["involved", "có liên quan"],
    ["depart", "khởi hành"],
    ["philosopher", "triết gia"],
    ["systematic", "thuộc hệ thống"],
    ["able", "có năng lực"],
    ["rubber", "cao su"],
    ["silk", "tơ ,lụa"],
    ["supply", "cung cấp, đáp ứng, tiếp tế"],
    ["safely", "an toàn, chắc chắn, đáng tin"],
    ["hang", "treo, mắc"],
    ["outdoor", "ngoài trời, ở ngoài"],
    ["controversial", "gây tranh cãi"],
    ["intense", "mãnh liệt"],
    ["politics", "chính trị"],
    ["locate", "xác định vị trí, định vị"],
    ["patrol", "tuần tra"],
    ["highly", "tốt, cao; hết sức, ở mức độ cao"],
    ["residential", "ký túc xá"],
    ["exchange", "tráo đổi"],
    ["resource", "tài nguyên; kế sách, thủ đoạn"],
    ["brotherhood", "hội gì?"],
    ["interval", "khoảng thời gian"],
    ["curly", "quăn, xoắn"],
    ["smell", "ngửi"],
    ["sour", "chua, cỏ vị giấm"],
    ["secret", "điều bí mật"],
    ["peanut", "di chuyển theo hình đậu phộng"],
    ["sunrise", "mặt trời mọc:"],
    ["barbecue", "tiệc nướng ngoài trời"],
    ["mend", "sửa chữa"],
    ["separation", "chia cắt, phân ly"],
    ["atmosphere", "khí quyến"],
    ["standard", "tiêu chuẩn"],
    ["surface", "bể mặt"],
    ["comma", "dấu phẩy"],
    ["tiring", "mệt mỏi"],
    ["equality", "bình đẳng"],
    ["excitement", "sự kích thích, sự kích động"],
    ["click", "bấm chuột"],
    ["ship", "tàu, tàu thủy"],
    ["uplifted", "được nâng lên"],
    ["uninterested", "không quan tâm"],
    ["publisher", "nhà xuất bản"],
    ["notorious", "khét tiếng"],
    ["enable", "kích hoạt"],
    ["record", "danh mục của kỷ lục hiện tại"],
    ["embarrass", "làm rắc rối, gây khó khăn"],
    ["explosion", "phát triển ồ ạt"],
    ["appeal", "lời kêu gọi"],
    ["stripe", "sọc, vằn, viển"],
    ["geography", "địa lý, khoa địa lý"],
    ["accomplish", "hoàn thành"],
    ["connect", "kết nối"],
    ["swarm", "tự tập bầy"],
    ["skyscraper", "nhà chọc trời"],
    ["reality", "sự thật, thực tế, thực tại"],
    ["worthwhile", "đáng giá"],
    ["intend", "ý định, có ý định"],
    ["humid", "ẩm"],
    ["lighter", "xà lan (xuồng) chở hàng"],
    ["shallow", "nông, cạn"],
  ],
  "B2": [
    ["environment", "môi trường"],
    ["achievement", "thành tựu"],
    ["opportunity", "cơ hội"],
    ["challenge", "thử thách"],
    ["confident", "tự tin"],
    ["negotiate", "đàm phán"],
    ["persuade", "thuyết phục"],
    ["reliable", "đáng tin cậy"],
    ["ambitious", "tham vọng"],
    ["look forward to", "mong chờ"],
    ["give up", "từ bỏ"],
    ["figure out", "tìm ra"],
    ["consequence", "hậu quả"],
    ["improve", "cải thiện"],
    ["compete", "cạnh tranh"],
    ["developing", "đang phát triển"],
    ["tyranny", "chuyên chế"],
    ["round", "tròn, vòng quanh, xung quanh"],
    ["darling", "cục cưng"],
    ["ample", "dồi dào, dư thừa"],
    ["weed", "cỏ dại"],
    ["suppress", "lược bỏ"],
    ["prosecute", "truy tố"],
    ["snore", "ngáy"],
    ["uncommon", "đặc biệt"],
    ["slang", "tiếng lóng"],
    ["bad-tempered", "xấu tính, dễ nồi cáu"],
    ["germ", "vi trùng"],
    ["bombing", "đánh bom"],
    ["impressionist", "trường phái ấn tượng"],
    ["chase", "xua đuổi"],
    ["falter", "chùn bước"],
    ["literal", "bằng chữ:"],
    ["collocation", "sự sắp xếp"],
    ["literally", "theo đúng nghĩa đen"],
    ["upgrade", "nâng cấp"],
    ["formerly", "trước đây, thuở xưa"],
    ["imagery", "hình ảnh"],
    ["nonprofessional", "không chuyên nghiệp"],
    ["cause", "gây ra:"],
    ["welfare", "phúc lợi"],
    ["amongst", "giữa"],
    ["educator", "nhà giáo dục"],
    ["hospitality", "lòng hiếu khách"],
    ["therapy", "trị liệu"],
    ["simplification", "sự đơn giản hóa"],
    ["known", "đã xác định"],
    ["geographic", "địa dư"],
    ["exhausting", "mệt mỏi"],
    ["mortal", "sinh tử"],
    ["prominence", "tình trạng nổi lên"],
    ["interpreter", "thông dịch viên"],
    ["amazement", "kinh ngạc"],
    ["adversity", "nghịch cảnh"],
    ["emphatically", "dứt khoát"],
    ["pancake", "bánh xèo"],
    ["inexperienced", "thiếu kinh nghiệm"],
    ["persuasion", "thuyết Phục"],
    ["proudly", "một cách tự hào, một cách hãnh diện"],
    ["reflective", "phản xạ"],
    ["dependable", "có thể tin được, đáng tin cậy"],
    ["bookmark", "dấu trang"],
    ["master", "thiết bị chính"],
    ["conductor", "vật dẫn"],
    ["stick", "đạt được cái gì"],
    ["posh", "hạng sang"],
    ["pave", "lát"],
    ["anguish", "nỗi thống khổ"],
    ["sunbeam", "tia nắng"],
    ["abuse", "lạm dụng"],
    ["micro", "siêu nhỏ"],
    ["confine", "giam giữ, hạn chế"],
    ["translator", "phiên dịch viên"],
    ["outpatient", "bệnh nhân ngoạỉ trú"],
    ["flesh", "thịt"],
    ["wearisome", "mệt mỏi"],
    ["strictly", "một cách nghiêm khắc"],
    ["divorce", "ly dị"],
  ],
  "C1": [
    ["sophisticated", "tinh vi, phức tạp"],
    ["inevitable", "không thể tránh khỏi"],
    ["ambiguous", "mơ hồ"],
    ["comprehensive", "toàn diện"],
    ["deteriorate", "xấu đi"],
    ["reluctant", "miễn cưỡng"],
    ["substantial", "đáng kể"],
    ["controversial", "gây tranh cãi"],
    ["meticulous", "tỉ mỉ"],
    ["put up with", "chịu đựng"],
    ["come up with", "nghĩ ra"],
    ["plausible", "có vẻ hợp lý"],
    ["flee", "chạy trốn"],
    ["fairness", "công bằng"],
    ["ironic", "rái cá"],
    ["proceeds", "tiền thu được"],
    ["logic", "lô gic"],
    ["well", "giỏi"],
    ["memoir", "bút ký"],
    ["scattered", "manh mún"],
    ["suburban", "giao, Dương Tuyền"],
    ["ritual", "nghi lễ"],
    ["cater", "phục vụ theo yêu cầu"],
    ["seal", "hải cầu; săn hải cầu"],
    ["gross", "tổng"],
    ["minimal", "tối thiểu"],
    ["prospective", "tiến cứu"],
    ["presently", "hiện tại"],
    ["inmate", "tù nhân"],
    ["beloved", "người yêu dấu"],
    ["assert", "khẳng định"],
    ["warfare", "chiến tranh"],
    ["whatsoever", "bất cứ chuyện gì"],
    ["forthcoming", "sap toi"],
    ["contemplate", "ngắm thành phố về đêm"],
    ["desktop", "mặt bàn giấy"],
    ["sheer", "da cừu"],
    ["withdrawal", "triệt tiêu"],
    ["motorist", "người lái xe máy"],
    ["toll", "tổn thất"],
    ["peculiar", "biệt"],
    ["variable", "biến đổi"],
    ["villager", "dân làng"],
    ["span", "nhịp"],
    ["trophy", "chiến lợi phẩm"],
    ["damaging", "có hại, hại"],
    ["overly", "quá mức"],
    ["correlation", "sự tương quan"],
    ["dimension", "kích thước"],
    ["vulnerability", "lỗ hổng"],
    ["magnetic", "từ tính"],
    ["accumulation", "ứ đọng"],
    ["quota", "chỉ tiêu"],
    ["parameter", "thông số"],
    ["contrary", "trái ngược"],
    ["motive", "động cơ"],
    ["prejudice", "gây tổn hại?"],
    ["occurrence", "lần xuất hiện"],
    ["productivity", "hiệu suất"],
    ["destructive", "phá hoại"],
    ["gallon", "galon"],
    ["capitalism", "sự tập trung tư bản (trong tay thiểu số)"],
    ["transparency", "tính minh bạch"],
    ["implementation", "thực thi"],
    ["administer", "quản lý"],
    ["seize", "nắm bắt"],
    ["upcoming", "sắp diễn ra"],
    ["feminist", "chủ nghĩa nam nữ bình quyền"],
    ["influential", "có ảnh hưởng sao?"],
    ["sphere", "hình cầu"],
    ["prevention", "sự ngăn cản"],
    ["assassination", "ám sát"],
    ["harassment", "quấy rối"],
    ["devil", "thịt rán quá lửa"],
    ["versus", "đấu với"],
    ["embark", "lên tàu"],
    ["inadequate", "không thích hợp"],
    ["stun", "làm choáng váng (súc vật trước khi mổ)"],
    ["correspondence", "thư từ qua lại"],
  ],
  "C2": [
    ["ubiquitous", "có mặt khắp nơi"],
    ["ephemeral", "phù du, ngắn ngủi"],
    ["idiosyncratic", "đặc trưng riêng"],
    ["pragmatic", "thực dụng"],
    ["disseminate", "phổ biến, truyền bá"],
    ["exacerbate", "làm trầm trọng thêm"],
    ["ostensibly", "bề ngoài thì"],
    ["equanimity", "sự bình thản"],
    ["indefatigable", "không biết mệt mỏi"],
    ["by and large", "nhìn chung"],
    ["captious", "bị giam cầm"],
    ["magnanimous", "cao thượng"],
    ["apotheosis", "thần thánh"],
    ["tirade", "đả kích"],
    ["gregarious", "thích giao du"],
    ["profligate", "hoang phí"],
    ["decry", "chê bai"],
    ["castigate", "hành hạ"],
    ["antipathy", "phản cảm"],
    ["mitigate", "giảm thiểu"],
    ["obdurate", "cứng nhắc"],
    ["prosaic", "tục tĩu"],
    ["morose", "rầu rĩ"],
    ["felicitous", "hạnh phúc"],
    ["pedantic", "mô phạm"],
    ["extant", "còn tồn tại"],
    ["obsequious", "khúm núm"],
    ["expatiate", "làm việc ở nước ngoài"],
    ["demagogue", "người mị dân"],
    ["burnish", "đánh bóng"],
    ["dubiety", "nghi ngờ"],
    ["languid", "uể oải"],
    ["flout", "hờn dỗi"],
    ["dissemble", "tháo rời"],
    ["expiate", "đền tội"],
    ["subvert", "lật đổ"],
    ["supercilious", "siêu phàm"],
    ["vacuous", "trống rỗng"],
    ["vilify", "phỉ báng"],
    ["superfluous", "thừa"],
    ["desiccate", "sấy"],
    ["abstruse", "khó hiểu"],
    ["ascetic", "thông tin về nhà sư minh tuệ"],
    ["insouciant", "không nổi bật"],
    ["excoriate", "bệnh da liễu"],
    ["relegate", "xuống hạng"],
    ["loquacious", "nói tục tĩu"],
    ["euphemism", "khinh từ"],
    ["dogmatic", "câu nệ giáo điều"],
    ["coalesce", "nối lại"],
    ["laud", "lời khen ngợi"],
    ["endemic", "địa phương"],
    ["sanctimonious", "thiêng liêng"],
    ["indolent", "vô cảm [tt]"],
    ["verbose", "dài dòng, dài dòng"],
    ["caustic", "kiềm ăn da"],
    ["onerous", "nặng nề"],
    ["hubris", "ngạo mạn"],
    ["solipsism", "thuyết duy ngã"],
    ["soporific", "thuốc ngủ"],
    ["desultory", "bỏ hoang"],
    ["bellicose", "bướng bỉnh"],
    ["antithesis", "phản đề"],
    ["remonstrate", "phản đối"],
    ["obviate", "tránh"],
    ["expunge", "xóa bỏ"],
  ],
};
